### ISSUE TITLE
When i click start it changes my date to 3 yrs back

### ISSUE THREAD

**Issue by procrafter820** [lihaoyun6/PD-Runner#100]
When i click start to any VM it changes my date to 3 yrs back and then i have to manually return back
It would be easier if it was automic

**Comment by lihaoyun6** [comment]
> When i click start to any VM it changes my date to 3 yrs back and then i have to manually return back
> It would be easier if it was automic

If everything is normal, the system date will be automatically corrected by PD Runner.  
If not, it means that there may be some problems. Please upload the logs.

**How to get logs:**
1. Right click "PD Runner. app", and then click "Show Package Contents"
2. Go to "Contents" > "MacOS" folder
3. Double click the "PD Runner" file to start PD Runner in verbose mode
4. Copy or screenshot the contents in the Terminal window, and then reply it to me

**Comment by lihaoyun6** [comment]
I haven't gotten a reply for a long time. So this issue will be closed.
