### ISSUE TITLE
遇到同样的问题，根据上面的建议 无法解决，PD升级到17.1.1 ，系统升级到12.1 Beta4>

### ISSUE THREAD

**Issue by soulxl** [lihaoyun6/PD-Runner#103]
> @olegvienna The feedback I received showed that others had encountered this problem. I analyzed those logs. Maybe for some reason, the Privileged Helper of PD Runner didn't work correctly. Try using this program to uninstall the Privileged Helper and try running PD Runner again. (If you still can't start the VM after doing this, please let me know)
> 
> [Uninstall-Helper.zip](https://github.com/lihaoyun6/PD-Runner/files/7638887/Uninstall-Helper.zip)

thx for reply. tried as u advised. same issue. just nothing happened. how can I see the logs?

_Originally posted by @olegvienna in https://github.com/lihaoyun6/PD-Runner/issues/102#issuecomment-984584706_

**Comment by lihaoyun6** [comment]
@soulxl 
macOS 12.1 Beta4的"time daemon"守护进程可能有bug. 
我今晚会在v0.2.14更新中加入对macOS 12.1 Beta4的支持.

There may be a bug in the "time daemon" of macOS 12.1 Beta4.
I will add support for mac OS 12.1 Beta4 in the PD Runner v0.2.14 tonight.

**Comment by soulxl** [comment]
> @soulxl macOS 12.1 Beta4的"time daemon"守护进程可能有bug. 我今晚会在v0.2.14更新中加入对macOS 12.1 Beta4的支持.
> 
> There may be a bug in the "time daemon" of macOS 12.1 Beta4. I will add support for mac OS 12.1 Beta4 in the PD Runner v0.2.14 tonight.

已完美解决，谢谢！
