### ISSUE TITLE
能不能关闭自动更新啊 至少不要强制升级

### ISSUE THREAD

**Issue by zsqw123** [lihaoyun6/PD-Runner#105]
每次开机都能看到作者发版，一看一天三个release，不更新还不让用，绷不住了，至少加个选项（（，或者别强制更新

**Comment by lihaoyun6** [comment]
> 每次开机都能看到作者发版，一看一天三个release，不更新还不让用，绷不住了，至少加个选项（（，或者别强制更新

可以, 下个版本加入这个开关

**Comment by lihaoyun6** [comment]
@zsqw123 
v0.2.15已发布, 加入了此功能
