### ISSUE TITLE
AppleScript - Stop All - not working

### ISSUE THREAD

**Issue by jackygoy** [lihaoyun6/PD-Runner#107]
AppleScript to stop all not working.

Version : 0.2.15

Result :
error "PD Runner got an error: The handler some object is not defined." number -1717

<img width="275" alt="Screenshot 2021-12-03 at 23 16 08 " src="https://user-images.githubusercontent.com/10493438/144626434-36683f51-578f-466b-b1fe-90d0c2ae199b.png">

**Comment by lihaoyun6** [comment]
@jackygoy 
I will fix this in the next release

**Comment by jackygoy** [comment]
@lihaoyun6 

Updated to version 0.3.4

same issue is happen again but this time no error message was throw, it just like nothing happen and vm is not stopping.
