### ISSUE TITLE
程序启动必须更新 这个可能去掉吗？

### ISSUE THREAD

**Issue by bdragonh** [lihaoyun6/PD-Runner#108]
有一些不是关键更新 ，是否可以 不用必须更新 。 只弹出更新日志。方便用户自己决定

**Comment by lihaoyun6** [comment]
> 有一些不是关键更新 ，是否可以 不用必须更新 。 只弹出更新日志。方便用户自己决定

0.2.15开始加入了"自动检查更新"开关. 关闭即可
