### ISSUE TITLE
2.16 Can't Start VM

### ISSUE THREAD

**Issue by lsafelix75** [lihaoyun6/PD-Runner#109]
When i click start VM from PD Runner nothing happens. Control Center blinks for a brief moment

**Comment by lihaoyun6** [comment]
> When i click start VM from PD Runner nothing happens. Control Center blinks for a brief moment

Please upload the log.

**How to get logs:**
1. Right click "PD Runner. app", and then click "Show Package Contents"
2. Go to "Contents" > "MacOS" folder
3. Double click the "PD Runner" file to start PD Runner in verbose mode
4. Copy or screenshot the contents in the Terminal window, and then reply it to me

**Comment by inoek** [comment]
I think I have a same problem. when I start VM I got a error today: You must have a trial version of Parallels Desktop installed.
Then you can run VMs with PD Runner even if the trial period expires

**Comment by lihaoyun6** [comment]
> I think I have a same problem. when I start VM I got a error today: You must have a trial version of Parallels Desktop installed.
> Then you can run VMs with PD Runner even if the trial period expires

Just like the literal meaning of this message. You need to log in to your Parallels Desktop account first, and get a 14-day free trial. This will give you a license, and PD Runner needs it.
What PD Runner does is to make Parallels Desktop trust your existing license unconditionally, instead of creating it out of nothing.

**Comment by lihaoyun6** [comment]
> When i click start VM from PD Runner nothing happens. Control Center blinks for a brief moment

I haven't gotten a reply for a long time. So this issue will be closed.
