### ISSUE TITLE
无法连接至 Parallels 服务

### ISSUE THREAD

**Issue by ioiioo** [lihaoyun6/PD-Runner#11]
<img width="480" alt="Snipaste_2021-10-29_18-06-51" src="https://user-images.githubusercontent.com/26021227/139417017-685b05e2-8fdb-4603-841e-388ff8bc34b6.png">

使用 PD Runner 启动刚从官网下载的 PD 17.1.0 ARM版本中的虚拟机, 打印虚拟机的界面一闪而过,之后就弹这个框

```
请确保 prl_disp_service 进程正在进行中，并且未被防火墙屏蔽。有关详情，请参阅这篇知识库文章。
```
<img width="688" alt="Snipaste_2021-10-29_18-09-58" src="https://user-images.githubusercontent.com/26021227/139417348-0150de7d-c1a9-45a7-9f15-be3d63748698.png">

<img width="889" alt="Snipaste_2021-10-29_18-10-54" src="https://user-images.githubusercontent.com/26021227/139417490-0c1638fd-9922-4f4b-8b2b-82c9eadfb4b7.png">

**Comment by xiaoker** [comment]
我也出现过这个问题，辛苦开发者

**Comment by lihaoyun6** [comment]
> 己解决,解决办法:
> 
> 试用已过期，去把系统时间改成 2021 年 9 月 1 号，然后运行 PD，弹出试用窗口的时候点击「继续试用」，然后把 PD 退出，系统时间改回来，再用启动器启动即可。

其实重启一下macOS系统也可以解决
