### ISSUE TITLE
这更新频率····

### ISSUE THREAD

**Issue by darvintang** [lihaoyun6/PD-Runner#110]

**Comment by lihaoyun6** [comment]
主要是修复bug和添加各种社区翻译, 偶尔加几个新功能.
因为Parallels Desktop的功能很庞杂. 我编程的时候不可能把每一个可能的功能都试一遍.
所以我只能保证PD Runner在我的使用范围内不出bug. 而没有为其他功能编写对应的代码.
属于是守株待兔方案: 等其他用户使用PD复杂功能出了bug, 我再根据他们的反馈来修bug.

**Comment by darvintang** [comment]
你加一个在线更新的功能吧，不然这每次更新都要自己重新下载也够麻烦的
