### ISSUE TITLE
v0.2.16, cannot start application, asks to update even though I'm on the latest version

### ISSUE THREAD

**Issue by 5HU8H** [lihaoyun6/PD-Runner#111]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/68404136/144705000-0f75b9e3-d247-4375-9670-2763a6dde6e0.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/68404136/144705011-8a9f1f92-ac5d-470e-b4c2-e8482da1462e.png">

**Comment by lihaoyun6** [comment]
@5HU8H 
I'm sorry, because I wrote an extra "v" in the release label.
You don't need to do anything, now the problem has been fixed.

**Comment by 5HU8H** [comment]
Thanks a lot! Love your work.
