### ISSUE TITLE
Parallels Desktop not installed

### ISSUE THREAD

**Issue by EmanueleA99** [lihaoyun6/PD-Runner#112]
I have already installed parallels desktop with a win11 VM on it, and after that i have download PD runner, the last version, but when I start it I see the message, Paralles desktop not installed. I have another 10 days of free license and i don't know why Pd runner can't see my Pdesktop. Do you have any idea to solve it? Thanks!

**Comment by lihaoyun6** [comment]
@EmanueleA99 
Where did you download Parallels Desktop from? 
PD Runner does not support the App Store Edition of Parallels Desktop. It can only work with the Standard Edition.

**Comment by lihaoyun6** [comment]
@EmanueleA99 
And please upload the log of PD Runner if you are using the Standard Edition of Parallels Desktop.

**How to get logs:**
1. Right click "PD Runner. app", and then click "Show Package Contents"
2. Go to "Contents" > "MacOS" folder
3. Double click the "PD Runner" file to start PD Runner in verbose mode
4. Copy or screenshot the contents in the Terminal window, and then reply it to me

**Comment by sheaahhoi1** [comment]
@lihaoyun6 
你好 與上述用家具有相同情狀
雖然我覺得以“詳細模式啟動PD Runner”
所記錄結果沒有作用但也提供

雖然閣下已支援Apple Silicon，但我懷疑是否全Apple Silicon 都支援，本人正在使用 M1 MAX 32GPU版

PS：其他訊息PD-Runner偵測不到M1 MAX 32GPU版上安裝版本PD17.1.1-51537，（PD-Runner呆滯）在啟動會阻礙運行虛擬機，第1訊息
找不到例“WIN11 ARM”（PD-Runner LOADING），之後到繼續阻礙PD17.1.1本體啟動大約數分鐘，之後PD本體關閉，（PD-Runner LOADING），約1分鐘後正常，以下記錄也只到找不到“WIN11 ARM”虛擬機前


`Last login: Sat Dec  4 20:08:12 on ttys000
MAC@HffafvMBP ~ % /Applications/PD\ Runner.app/Contents/MacOS/PD\ Runner ; exit;
2021-12-04 20:40:21.5120 Remote Version: 0.2.16
2021-12-04 20:40:21.5130 Check helper status...
2021-12-04 20:40:21.5140 Helper installed.
2021-12-04 20:40:21.5150 Run loop...
2021-12-04 20:40:21.5190 Parallels Desktop not installed!
2021-12-04 20:40:21.5520 Installed version: 0.1.12, InBundle version: 0.1.12
2021-12-04 20:40:21.5520 Helper installed.`

**Comment by EmanueleA99** [comment]
> 

Sorry, it's my fault. I've download app store version instead standard Edition. Can I download standard Edition without delete my vm?

**Comment by EmanueleA99** [comment]
Thanks! I've download the standard version from the parallels site and now it works perfectly! Thanks a lot!

**Comment by lihaoyun6** [comment]
> Sorry, it's my fault. I've download app store version instead standard Edition. Can I download standard Edition without delete my vm?
<img width="1212" alt="Xnip2021-12-04_21-54-58" src="https://user-images.githubusercontent.com/16348097/144712102-c64931ca-ec0b-45d5-b6d0-df44e50615c3.png">
Your virtual machines will not be affected by uninstalling Parallels Desktop.
So you can simply uninstall Parallels Desktop for App Store Edition.
Then install the Standard Edition and import your VMs.

**Comment by lihaoyun6** [comment]
@sheaahhoi1 
此issue已被发起人关闭, 为了方便后续的问题追踪和交流. 可以请您单独提交一个issue议题吗? 感谢您的支持
