### ISSUE TITLE
v0.2.16 找不到PD

### ISSUE THREAD

**Issue by sheaahhoi1** [lihaoyun6/PD-Runner#114]
@lihaoyun6
你好 
雖然我覺得以“詳細模式啟動PD Runner”
所記錄結果沒有作用但也提供

雖然閣下已支援Apple Silicon，但我懷疑是否全Apple Silicon 都支援，本人正在使用 M1 MAX 32GPU版

PS：其他訊息PD-Runner偵測不到M1 MAX 32GPU版上安裝版本PD17.1.1-51537，（PD-Runner呆滯）在啟動會阻礙運行虛擬機，第1訊息
找不到例“WIN11 ARM”（PD-Runner LOADING），之後到繼續阻礙PD17.1.1本體啟動大約數分鐘，之後PD本體關閉，（PD-Runner LOADING），約1分鐘後正常，以下記錄也只到找不到“WIN11 ARM”虛擬機前

Last login: Sat Dec 4 20:08:12 on ttys000
MAC@HffafvMBP ~ % /Applications/PD\ Runner.app/Contents/MacOS/PD\ Runner ; exit;
2021-12-04 20:40:21.5120 Remote Version: 0.2.16
2021-12-04 20:40:21.5130 Check helper status...
2021-12-04 20:40:21.5140 Helper installed.
2021-12-04 20:40:21.5150 Run loop...
2021-12-04 20:40:21.5190 Parallels Desktop not installed!
2021-12-04 20:40:21.5520 Installed version: 0.1.12, InBundle version: 0.1.12
2021-12-04 20:40:21.5520 Helper installed.

**Comment by lihaoyun6** [comment]
@sheaahhoi1 
方便在终端中执行这条命令, 然后给我看一下结果吗  
```bash
file "/Applications/Parallels Desktop.app/Contents/MacOS/parallels_wrapper"
```

**Comment by sheaahhoi1** [comment]
MBP ~ % file "/Applications/Parallels Desktop.app/Contents/MacOS/parallels_wrapper"

/Applications/Parallels Desktop.app/Contents/MacOS/parallels_wrapper: cannot open `/Applications/Parallels Desktop.app/Contents/MacOS/parallels_wrapper' (No such file or directory)

**Comment by lihaoyun6** [comment]
@sheaahhoi1 您确定安装的是从parallels网站下载的标准版PD，而不是来自App Store的版本吗

**Comment by sheaahhoi1** [comment]
是從官網下載但看似不是標準版，結尾寫PRO版
![螢幕截圖 2021-12-05 上午9 17 07](https://user-images.githubusercontent.com/10239384/144729742-f20ea6a6-960a-428e-a23c-6f34e3ccef23.png)

MBP ~ % ls /Applications/Parallels\ Desktop.app/Contents/MacOS

ls: /Applications/Parallels Desktop.app/Contents/MacOS: No such file or directory

**Comment by sheaahhoi1** [comment]
我想起最初是從這裡下載
Parallels® Desktop for Mac Business Edition（這邊是離線版）
[https://www.parallels.com/hk/products/business/](url)
好像和首頁版不同，剛在首頁重新下載（在線安裝版）則成功

**Comment by lihaoyun6** [comment]
@sheaahhoi1 
虽然很不可思议, 但是命令执行的结果显示您的"應用程式"資料夾中并不存在名为Parallels Desktop的應用程式. 您确定PD安装位置正确吗?

**Comment by sheaahhoi1** [comment]
的確"應用程式"資料夾內是沒有，只留在DOCK，所以我到官網首頁重新下載現在PD-Runner成功運行了
