### ISSUE TITLE
Activity monitor使用时间显示错误

### ISSUE THREAD

**Issue by jimmychuichui** [lihaoyun6/PD-Runner#115]
@lihaoyun6 
你好！
每次我使用PD Runner启动虚拟机后，Activity monitor里面的使用时间都会显示非常大的数字，且Usage History都会被清除
望修复，谢谢🙏
<img width="640" alt="Screen Shot 2021-12-04 at 5 41 58 PM" src="https://user-images.githubusercontent.com/60454148/144730159-b80fae80-abc8-4d4c-9ce0-71c84f1d3577.png">
<img width="656" alt="Screen Shot 2021-12-04 at 5 44 06 PM" src="https://user-images.githubusercontent.com/60454148/144730251-3f1befe4-7fe7-4d75-96e2-8037dbeb96c7.png">

**Comment by lihaoyun6** [comment]
@jimmychuichui 
这个暂时没有什么太好的解决方式. 因为PD Runner绕过PD激活机制的核心操作就是在合适的时候"对系统时间进行修改"并且"在正确的时机启动虚拟机".
所以修改系统时间这个操作是不可避免会发生的. 没有这个操作, 就不能生效.

**Comment by lihaoyun6** [comment]
@jimmychuichui 
我在v0.3.0版本中尽可能的缩短了改变系统日期的持续时间. 你再试试看吧

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue
