### ISSUE TITLE
启动之后窗口没任何东西也没任何提示

### ISSUE THREAD

**Issue by SampsonJava** [lihaoyun6/PD-Runner#116]
PD版本 17.1.1 (51537)
Window10
PD Runner下载的最新的
macOS版本12.0.1
型号M1 Pro

**Comment by lihaoyun6** [comment]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/16348097/144734902-4a45d83c-2b60-4cfc-a42a-f17ac9e9243e.png">

**Comment by SampsonJava** [comment]
我指的没任何东西,是说的菜单栏app那边的图标呀,没任何变化

**Comment by SampsonJava** [comment]
我是mbp14 我点了刘海里面,一样啥也没有

**Comment by lihaoyun6** [comment]
@SampsonJava 重启一下Mac试试?

**Comment by SampsonJava** [comment]
重启试过几次了,是不支持最新版pd了吗,还是说win10的问题

**Comment by lihaoyun6** [comment]
> 重启试过几次了,是不支持最新版pd了吗,还是说win10的问题

PD Runner支持最新版的macOS和最新版的PD.
请检查一下看看PD Runner是否启动了(可以在"活动监视器"里看一下)

**Comment by SampsonJava** [comment]
![image](https://user-images.githubusercontent.com/35320236/144739645-69f410d4-988b-4725-9f70-6b1ea5aa72c3.png)

**Comment by lihaoyun6** [comment]
@SampsonJava 
请首先确认您没有安装菜单栏图标管理类软件. 如果安装了此类软件, 那么可能是由于它自动把PD Runner的图标收起了.
如果确认没有安装类似的软件, 那么请提供一下运行日志, 方便我进行排错. 

**获取日志的方法为:**  
1. 在活动监视器中结束PD Runner的进程
2. 右键单击PD Runner的文件, 选择"显示包内容". 
3. 依次进入Contents > MacOS目录并双击其中的"PD Runner"文件
4. 把弹出窗口中的日志信息复制或截图发上来就可以了

**Comment by SampsonJava** [comment]
好了,菜单栏东西太多,导致pd图标消失了,退出了一些就显示出来了
