### ISSUE TITLE
macos monterey 12.0.1版本安装PD-Runner启动windows10虚拟机，mac与虚拟机播放视频没声音

### ISSUE THREAD

**Issue by classcit** [lihaoyun6/PD-Runner#117]
macos monterey 12.0.1版本安装PD-Runner启动windows10虚拟机，PD版本 17.1.1 (51537)，系统运行一段时间，看一会儿电影（一切正常），关闭电影网站，待机一会儿，重新打开看视频，此时mac与虚拟机播放视频都没声音，mac外部视频也都一直无法播放，退出PD-Runner+关闭虚拟机后问题消失，也不知道是啥问题导致的。

**Comment by lihaoyun6** [comment]
应该是Parallels Desktop的bug, 不是PD Runner的

**Comment by classcit** [comment]
慢慢摸索尝试，还是google好，找到答案了。
https://www.xiefeng.org/post/24.html
