### ISSUE TITLE
pd-runner hang

### ISSUE THREAD

**Issue by me450722457** [lihaoyun6/PD-Runner#118]
使用版本：0.2.16

使用期间，发现如果有虚拟机启动时间过长，会导致pd-runner主程序hang，鼠标转圈。可否改成点击"启动"按钮后立即返回，不等待启动结果，有异常再报错。

**Comment by lihaoyun6** [comment]
> 使用版本：0.2.16
> 
> 使用期间，发现如果有虚拟机启动时间过长，会导致pd-runner主程序hang，鼠标转圈。可否改成点击"启动"按钮后立即返回，不等待启动结果，有异常再报错。

可以考虑, 加入多线程支持

**Comment by me450722457** [comment]
> > 使用版本：0.2.16
> > 使用期间，发现如果有虚拟机启动时间过长，会导致pd-runner主程序hang，鼠标转圈。可否改成点击"启动"按钮后立即返回，不等待启动结果，有异常再报错。
> 
> 可以考虑, 加入多线程支持

谢谢支持

**Comment by lihaoyun6** [comment]
@me450722457 
最新的v0.3.1版本已经解决了这个问题. 把启动虚拟机操作从主线程剥离, 交给子线程来做. 虚拟机启动时间过长也不会导致菜单假死了.
