### ISSUE TITLE
更新到最新版本,一直在安装完成的界面。不能启动了

### ISSUE THREAD

**Issue by gwaiting** [lihaoyun6/PD-Runner#119]
<img width="1440" alt="Screen Shot 2021-12-06 at 14 07 15" src="https://user-images.githubusercontent.com/51308621/144795965-54ccbf57-4e2f-4692-bc82-40bc05bbfdfe.png">

**Comment by gwaiting** [comment]
# 已解决
## 如果试用已过期
### 去把系统时间改成 2021 年 9 月 1 号，然后运行 PD，弹出试用窗口的时候点击「继续试用」，然后把 PD 退出，系统时间改回来，再用启动器启动即可。

**Comment by lihaoyun6** [comment]
> <img alt="Screen Shot 2021-12-06 at 14 07 15" width="1440" src="https://user-images.githubusercontent.com/51308621/144795965-54ccbf57-4e2f-4692-bc82-40bc05bbfdfe.png">

创建虚拟机的时候一定要记得勾选"手动安装操作系统". 就不会卡在这里了

**Comment by gwaiting** [comment]
> ### 去把系统时间改成 2021 年 9 月 1 号，然后运行 PD，弹出试用窗口的时候点击「继续试用」，然后把 PD 退出，系统时间改回来，再用启动器启动即可。

是的呢简，简直非常感谢你。但是我在哔哩哔哩视频网站上面看到一些。视频作者用这个来进行收费和获取利益？作者，你不去投诉和举报他吗？
