### ISSUE TITLE
macw 网站在打包您的软件以提供付费下载

### ISSUE THREAD

**Issue by hywhuangyuwei** [lihaoyun6/PD-Runner#12]
![image](https://user-images.githubusercontent.com/33554665/139417333-ac0a8cc4-12ef-4ec1-9db4-dc2b0ac29554.png)
![image](https://user-images.githubusercontent.com/33554665/139417428-e79afe6b-3923-456a-a7d6-a2244def5006.png)
![image](https://user-images.githubusercontent.com/33554665/139417372-49fa9dec-59ee-45ea-89e6-f38cde6084b4.png)
![image](https://user-images.githubusercontent.com/33554665/139417471-4ac3fce9-378f-449f-be1c-1cf78a1d9ee7.png)

**Comment by lihaoyun6** [comment]
经过交涉已解决此问题, 故关闭此issue, 感谢您的支持与提醒.
