### ISSUE TITLE
常见问题，中文翻译。

### ISSUE THREAD

**Issue by gwaiting** [lihaoyun6/PD-Runner#120]
# 关于PD：
去 PD 官网下载 PD 17 试用版：点我去下载(支持 Parallels Desktop 17.1)
下载完成后安装，安装完成后运行 PD（要登录一下账号！！！如果没有账号，去注册一个 pd 的账号，然后登录，登录后点试用，会送你 14 天试用）。
然后安装 Windows 虚拟机或者 linux/Ubuntu 虚拟机（未安装虚拟机的一定要先安装虚拟机，安装过的可以跳过这一步）。
彻底退出运行的 PD (不会的直接重启电脑)，然后运行安装的 「PD Runner」，在菜单栏会出现一个类似播放器的图标，点击它，再点击需要启动的虚拟机即可。
# 注意事项：
### 如果试用已过期，去把系统时间改成 2021 年 9 月 1 号，然后运行 PD，弹出试用窗口的时候点击「继续试用」，然后把 PD 退出，系统时间改回来，再用启动器启动即可。
为了方便使用你可以打开启动台，将 PD Runner 拖到你的 Dock 栏中（程序坞），启动器无视试用到期，也不用修改系统时间，就算到期了也一样可以用。
### 什么首次启动会需要输入密码?
因为针对PD 17.1.0新引入的鉴权措施, 需要通过快速切换系统时间来绕过. 所以需要向系统中安装一个特权助理, 方便进行修改时间的操作. 如果不这样做, 那么每次启动虚拟机的时候就都需要输入一次密码.
### 为什么PD Runner启动后没有任何窗口?
因为PD Runner是一款菜单栏APP, 启动后只会在菜单栏显示一个图标以供使用, 并没有主窗口.
### 虚拟机需要修改为指定的名称才能使用吗?
不需要, PD Runner可以全自动识别当前系统中的客户机, 并自动列出. 不要用户干预.
### 错误 Domain=CFError DomainLaunchd Code=9 怎么办?
打开"终端"应用程序
复制并粘贴以下代码到终端中，然后回车: sudo launchctl enable system/com.lihaoyun6.PD-Runner-Helper
然后在 Password 钥匙图标后面输入你的电脑开机密码 (密码输入的过程中是看不到的)，输入完成后后回车。
再次启动 PD Runner 既可正常使用。
# 关于启动器：
此工具来自「lihaoyun6」的免费分享，如果您是在淘宝/咸鱼等地方购买的，请联系其退款并进行举报。
此工具非破解工具，只是使用了 PD 官方提供的方法启动。
关于 ARM M1 安装 Windows：
ARM M1 只能安装 Arm 架构的 windows 或者 linux 系统 ！！！
关于 Intel 安装 Windows：
请直接去微软官方下载镜像即可。

**Comment by xiaobai151** [comment]
? 不是有中文吗？

**Comment by lihaoyun6** [comment]
长时间未更新, 故关闭此issue
