### ISSUE TITLE
pd runner 0.3.1. new virtual machine installation

### ISSUE THREAD

**Issue by puma791** [lihaoyun6/PD-Runner#122]
after the trial period, I try to create a new virtual machine, the installation is successful, complete installation click to continue, it remains blocked.

**Comment by lihaoyun6** [comment]
> after the trial period, I try to create a new virtual machine, the installation is successful, complete installation click to continue, it remains blocked.

<img width="984" alt="Xnip2021-12-02_11-37-36" src="https://user-images.githubusercontent.com/16348097/144353415-71247706-3213-4663-8db7-fd61fe9e4f80.png">

When you create a virtual machine, be sure to check "Install operating system manually", otherwise it will be stuck in the last step.

**Comment by puma791** [comment]
Ok..Thank you
> 
> When you create a virtual machine, be sure to check "Install operating system manually", otherwise it will be stuck in the last step.

**Comment by puma791** [comment]
I created a new virtual machine with pd runner 0.3.2, the written installation wizard continues to work, but with manual installation everything is ok.
