### ISSUE TITLE
恢复快照的问题

### ISSUE THREAD

**Issue by 368573607** [lihaoyun6/PD-Runner#123]
![image](https://user-images.githubusercontent.com/60562136/145046611-ff2e50fc-ad27-420d-830c-36773c581edb.png)

如图，我想恢复一个快照，但只有一个取消选项

**Comment by lihaoyun6** [comment]
@368573607 已经定位到bug所在的代码段了, 正在修复.

**Comment by lihaoyun6** [comment]
@368573607 
此bug已经在v0.3.2版本中修复了
