### ISSUE TITLE
无法连接到pd17服务

### ISSUE THREAD

**Issue by hhy1106** [lihaoyun6/PD-Runner#125]
试过下梯子，关闭防火墙，能正常打开pd17但是pdrunner无法检测到pd17服务，
状态栏pd runner 显示 [无法连接到parallels服务]

**Comment by lihaoyun6** [comment]
@hhy1106 
请尝试在终端执行下面这条命令, 并将执行结果贴上来  
```bash
/usr/local/bin/prlctl list -ao name,-,-,-,-,ostemplate,-,-,-,-,uuid -s uuid 2>/dev/null|sed 's/[ ]*-[ ]*/-/g;s/----/:/g'
```

**Comment by hhy1106** [comment]
无返回

**Comment by hhy1106** [comment]
> @hhy1106 请尝试在终端执行下面这条命令, 并将执行结果贴上来
> 
> ```shell
> /usr/local/bin/prlctl list -ao name,-,-,-,-,ostemplate,-,-,-,-,uuid -s uuid 2>/dev/null|sed 's/[ ]*-[ ]*/-/g;s/----/:/g'
> ```
没有返回结果

**Comment by lihaoyun6** [comment]
@hhy1106 
那再试试这样  
```bash
/usr/local/bin/prlctl list -ao name,-,-,-,-,ostemplate,-,-,-,-,uuid -s uuid|sed 's/[ ]*-[ ]*/-/g;s/----/:/g'
```

**Comment by hhy1106** [comment]
> @hhy1106 那再试试这样
> 
> ```shell
> /usr/local/bin/prlctl list -ao name,-,-,-,-,ostemplate,-,-,-,-,uuid -s uuid|sed 's/[ ]*-[ ]*/-/g;s/----/:/g'
> ```

zsh: permission denied: /usr/local/bin/prlctl
返回如上

**Comment by lihaoyun6** [comment]
@hhy1106 
请再执行一下这个命令试试  
```bash
ls -l /usr/local/bin/prlctl
```

**Comment by hhy1106** [comment]
> @hhy1106 请再执行一下这个命令试试
> 
> ```shell
> ls -l /usr/local/bin/prlctl
> ```
total 0
返回如上

**Comment by lihaoyun6** [comment]
@hhy1106 
但是实际上应该显示这样才是正常的  
<img width="980" alt="Xnip2021-12-08_15-55-38" src="https://user-images.githubusercontent.com/16348097/145170240-3dba8a39-3f4a-4136-a7bf-96f2a97d82d6.png">

**Comment by lihaoyun6** [comment]
@hhy1106 
我也很奇怪, `total 0`这个也不是文件不存在的错误提示(文件不存在的话应该提示'ls: /usr/local/bin/prlctl: No such file or directory')

**Comment by hhy1106** [comment]
> 

是不是我的pd17没有安装到正确位置

**Comment by lihaoyun6** [comment]
@hhy1106 
如果可以的话, 我想用即时性更高的软件来辅助调试一下.  
比如QQ或者teamviewer之类的...但是奈何issue是公开的, 在这里放这些信息都不太好

**Comment by hhy1106** [comment]
> /usr/local/bin

我们qq聊吧，现在在学校用校园网有点卡，teamviewer操作不了

**Comment by lihaoyun6** [comment]
@hhy1106 
您加这个群吧. 这是我的一个软件交流群769199414
