### ISSUE TITLE
使用过期了虚拟机已暂停问题

### ISSUE THREAD

**Issue by sxf5487** [lihaoyun6/PD-Runner#127]
您好，我打开虚拟机后，提示已暂停，如图：
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/50735006/145173757-e4b4e573-b686-41e9-9ce9-07d5f127cfbc.png">

**Comment by rayborng** [comment]
我也有同样的问题

> 您好，我打开虚拟机后，提示已暂停，如图： <img alt="image" width="1280" src="https://user-images.githubusercontent.com/50735006/145173757-e4b4e573-b686-41e9-9ce9-07d5f127cfbc.png">

我也有同样的问题

**Comment by lihaoyun6** [comment]
@sxf5487 @rayborng 
再用PD Runner对这个虚拟机"启动"一次就好了. 
PD Runner的"启动"按钮不仅可以"开机", 还可以"唤醒"和"恢复"

**Comment by sxf5487** [comment]
好的。
