### ISSUE TITLE
virtual machine creation

### ISSUE THREAD

**Issue by puma791** [lihaoyun6/PD-Runner#128]
I created a new virtual machine with pd runner 0.3.2, the written installation wizard continues to work, but with manual installation everything is ok.
<img width="1025" alt="Schermata 2021-12-08 alle 11 54 44" src="https://user-images.githubusercontent.com/95686245/145211880-ab34cc92-fe2f-44bd-bace-b8ad8ede46f8.png">

"installation wizard"
<img width="1025" alt="Schermata 2021-12-08 alle 14 54 17" src="https://user-images.githubusercontent.com/95686245/145220256-57d971b0-a360-4944-bd4a-39b6b20e6649.png">

Network initialization failed

Virtual Hard Drive 1 has the wrong access permissions or is used with another virtual machine.

**Comment by puma791** [comment]
Italian language

Inviato da iPhone 12 Pro

**Comment by puma791** [comment]
installation wizard

Network initialization failed

Virtual Hard Drive 1 has the wrong access permissions or is used with another virtual machine.

**Comment by lihaoyun6** [comment]
@puma791 
If you are stuck at the last step when using the installation wizard to install the VM (It will say "click to continue" but you will never be able to continue).
You can try PD Runner v0.3.2 or higher. These versions of PD Runner can help you automatically skip the last phase of the installation wizard. Then you can directly enter the desktop of the VM.

**Comment by lihaoyun6** [comment]
@puma791 
However, I don't know how the disk warning shown in the screenshot happened.  
It may or may not be caused by a problem with Parallels Desktop. But it should not be caused by PD Runner
