### ISSUE TITLE
虚拟机系统有使用密码加密的似乎无法正常打开 

### ISSUE THREAD

**Issue by KyoShio** [lihaoyun6/PD-Runner#13]
![image](https://user-images.githubusercontent.com/20240090/139557528-1307864d-9e4f-41b3-91d3-f91751dc5d8d.png)

**Comment by lihaoyun6** [comment]
对于加密虚拟机的支持将在v0.1.12版本中正式加入

**Comment by lihaoyun6** [comment]
已经在v0.1.12版本中加入针对处于"加密"状态的虚拟机的支持, 在启动这类虚拟机时会弹出输入框请求用户手动输入密码
![EAA85A6090E5F7A982633F14B023E790](https://user-images.githubusercontent.com/16348097/139594177-2a81b70e-87ac-4315-bc9f-7dcb91ffa911.jpg)

**Comment by KyoShio** [comment]
输完密码还是打不开，只能手动再点下启动，又提示输密码

**Comment by KyoShio** [comment]
@lihaoyun6 https://user-images.githubusercontent.com/16348097/139594177-2a81b70e-87ac-4315-bc9f-7dcb91ffa911.jpg这个不行啊，输完密码，无法打开系统，得再手动点一下启动按钮，又提示输密码
