### ISSUE TITLE
不支持pd的安卓

### ISSUE THREAD

**Issue by dnvcupid** [lihaoyun6/PD-Runner#130]
![image](https://user-images.githubusercontent.com/4282818/145205985-c73f6f75-87f6-4525-884d-4cb347372a14.png)

本打算安装个安卓测试一下东西，然后发现不支持

**Comment by lihaoyun6** [comment]
@dnvcupid 
我目前在单位, 身边没有intel架构的Mac, 暂时无法进行调试.
今天晚上回家之后, 我会对这个问题进行调试

**Comment by libopenggggg** [comment]
> ![image](https://user-images.githubusercontent.com/4282818/145205985-c73f6f75-87f6-4525-884d-4cb347372a14.png)
> 
> 
> 
> 本打算安装个安卓测试一下东西，然后发现不支持

遇到同样问题 确实是这种情况 无法点击开机

**Comment by lihaoyun6** [comment]
@dnvcupid @libopenggggg 
已经在v0.3.3版本中修复了. 但是现在还在做稳定性测试, 暂时没有发布更新. 等到更新发布, 下载安装即可

**Comment by libopenggggg** [comment]
感谢



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月10日 23:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [lihaoyun6/PD-Runner] 不支持pd的安卓 (Issue #130) |

@***@***.***
已经在v0.3.3版本中修复了. 但是现在还在做稳定性测试, 暂时没有发布更新. 等到更新发布, 下载安装即可

**Comment by lihaoyun6** [comment]
@dnvcupid @libopenggggg 
v0.3.3版本已更新, 下载安装即可支持Android虚拟机
