### ISSUE TITLE
命令行启动虚拟机

### ISSUE THREAD

**Issue by hugo2lee** [lihaoyun6/PD-Runner#135]
pd 有个命令 prlctl start ubuntu, 可快速启动虚拟机不显示界面, 全程静默运行.
不知 PD-Runner 有考虑支持吗?

**Comment by me450722457** [comment]
我这边17.0.1的prlctl start 命令也是会弹出虚拟机界面的
pd-runner 1.x版本是通过调用这个命令来启动虚拟机的，2.x应该也是

**Comment by lihaoyun6** [comment]
> pd 有个命令 prlctl start ubuntu, 可快速启动虚拟机不显示界面, 全程静默运行.
> 不知 PD-Runner 有考虑支持吗?

我为PD Runner创建了AppleScript接口. 可以通过AppleScript来调用PD Runner进行开机等操作.
不过目前还没有对"静默启动"做什么支持, 如果有这个需求的用户多的话, 可能会考虑加入.

关于PD Runner的AppleScript接口用法可以看[这里](https://github.com/lihaoyun6/PD-Runner/blob/main/AppleScript.md)
