### ISSUE TITLE
启动Boot Camp即退出，其他虚拟机则不会

### ISSUE THREAD

**Issue by lsz231** [lihaoyun6/PD-Runner#136]
只有BootCamp会这样

**Comment by lihaoyun6** [comment]
@lsz231 
我现在是一台M1 Macmini + 一台intel iMac. 但是iMac是TB3外接SSD, 不支持BootCamp...所以没有可以安装bootcamp的设备. 对于这个问题很难调试

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue
