### ISSUE TITLE
PD Runner stopped working the next day

### ISSUE THREAD

**Issue by gabriellopescb** [lihaoyun6/PD-Runner#139]
Hi, I would like to know how to keep PD Runner working always, since I opened it today and it stopped, I had to install Parallels again.

**Comment by lihaoyun6** [comment]
@gabriellopescb 

Sorry, I did not understand what happened, please tell me more details:
1. What happened?
2. Does this happen every time?
3. Have you tried reinstalling PD Runner?

**Comment by gabriellopescb** [comment]
I think it worked here, thank you very much for your attention!

Em sex., 10 de dez. de 2021 às 07:41, lihaoyun6 ***@***.***>
escreveu:

**Comment by lihaoyun6** [comment]
> I think it worked here, thank you very much for your attention!  
😁Thank you for your support.
