### ISSUE TITLE
12系统打开PD启动器菜单栏无反应

### ISSUE THREAD

**Issue by jacoryhub** [lihaoyun6/PD-Runner#14]
我是12系统打开PD启动器菜单栏无反应，前几天打开PD启动器是正常的菜单栏有显示，现在怎么打开都不显示了，卸载了PD虚拟机和启动器重新安装，故障还是一样。

请教一下有没有遇到这种情况，目前PD虚拟机试用期还有9天，是12的系统影响了么。

**Comment by jacoryhub** [comment]
10月26号 12系统出来就升级了，启动器也是用了三四天，今天发现打开PD启动器，菜单栏没有显示启动器的图标。

**Comment by lihaoyun6** [comment]
有尝试过升级PD Runner到v0.1.11吗，这个版本修复了一个在macOS 12上会导致闪退的bug。

**Comment by zhixuans** [comment]
> 有尝试过升级PD Runner到v0.1.11吗，这个版本修复了一个在macOS 12上会导致闪退的bug。

我想问一个问题，是不是假如我的系统是装在u盘里面，我如果不插u盘，运行PD runner的话，是不会有图标的？我更新到0.1.11还是会这样。如果设计如此的话，就没什么问题，我之前以为是bug。

**Comment by lihaoyun6** [comment]
> > 有尝试过升级PD Runner到v0.1.11吗，这个版本修复了一个在macOS 12上会导致闪退的bug。
> 
> 我想问一个问题，是不是假如我的系统是装在u盘里面，我如果不插u盘，运行PD runner的话，是不会有图标的？我更新到0.1.11还是会这样。如果设计如此的话，就没什么问题，我之前以为是bug。

正常来说, 不管是没安装PD, 还是检测不到虚拟机, 都不会导致闪退, 菜单栏都是应该有图标的...

**Comment by lihaoyun6** [comment]
> > 有尝试过升级PD Runner到v0.1.11吗，这个版本修复了一个在macOS 12上会导致闪退的bug。
> 
> 我想问一个问题，是不是假如我的系统是装在u盘里面，我如果不插u盘，运行PD runner的话，是不会有图标的？我更新到0.1.11还是会这样。如果设计如此的话，就没什么问题，我之前以为是bug。

已经定位到问题了, 正在复现并尝试解决

**Comment by lihaoyun6** [comment]
> > 有尝试过升级PD Runner到v0.1.11吗，这个版本修复了一个在macOS 12上会导致闪退的bug。
> 
> 我想问一个问题，是不是假如我的系统是装在u盘里面，我如果不插u盘，运行PD runner的话，是不会有图标的？我更新到0.1.11还是会这样。如果设计如此的话，就没什么问题，我之前以为是bug。

已经找到并解决了这个问题, 处于"失联"状态的虚拟机无法读出系统信息, 会导致程序中的一个数组产生访问越界, 导致程序闪退. 已经在v0.1.12版本中修复了, 为失联状态的虚拟机添加了一种状态. 可以去下载使用一下看看
![D69C97262A6D97B8B64F72CF7EBD1038](https://user-images.githubusercontent.com/16348097/139594109-944a9e90-7328-4ca7-b94c-54095f4e2495.jpg)

**Comment by zhixuans** [comment]
> > > 有尝试过升级PD Runner到v0.1.11吗，这个版本修复了一个在macOS 12上会导致闪退的bug。
> > 
> > 
> > 我想问一个问题，是不是假如我的系统是装在u盘里面，我如果不插u盘，运行PD runner的话，是不会有图标的？我更新到0.1.11还是会这样。如果设计如此的话，就没什么问题，我之前以为是bug。
> 
> 已经找到并解决了这个问题, 处于"失联"状态的虚拟机无法读出系统信息, 会导致程序中的一个数组产生访问越界, 导致程序闪退. 已经在v0.1.12版本中修复了, 为失联状态的虚拟机添加了一种状态. 可以去下载使用一下看看 ![D69C97262A6D97B8B64F72CF7EBD1038](https://user-images.githubusercontent.com/16348097/139594109-944a9e90-7328-4ca7-b94c-54095f4e2495.jpg)

可以了，谢谢大佬

**Comment by jacoryhub** [comment]
> 有尝试过升级PD Runner到v0.1.11吗，这个版本修复了一个在macOS 12上会导致闪退的bug。
升级PD Runner到v0.1.12，问题已经解决，感谢大佬的辛苦成果。
