### ISSUE TITLE
GET TRIAL FIRST

### ISSUE THREAD

**Issue by nomecreonada** [lihaoyun6/PD-Runner#140]
My problem is that I installed PD Runner after the Parallels license expired, and although I create another user and reinstall Parallels, it always detects that there was a previous installation and does not offer me the 14-day trial, therefore PD Runner it does not work. Is there a way to install Parallels without detecting a previous installation? Thanks for your time.

**Comment by nomecreonada** [comment]
The solution is to change the date of the mac to a valid date of the trial period, then run PD then turn off the VM and we can put the correct date back on the mac.

**Comment by lihaoyun6** [comment]
> The solution is to change the date of the mac to a valid date of the trial period, then run PD then turn off the VM and we can put the correct date back on the mac.

🎉Congratulations, you did it exactly right.

**Comment by nomecreonada** [comment]
You only have to change the date once and temporarily, once you have run a VM with PD runner, close the VM put the correct time, from there the VMs will work with PD runner without having to change the date again.

**Comment by vahid-saeed** [comment]
this solution not work any more
