### ISSUE TITLE
在删除macOS虚拟机后 在菜单栏仍然存在macOS虚拟机

### ISSUE THREAD

**Issue by xiaobai151** [lihaoyun6/PD-Runner#141]
希望加回之前的手动刷新虚拟机列表

**Comment by lihaoyun6** [comment]
> 希望加回之前的手动刷新虚拟机列表

刷新菜单的时间间隔是5秒一次，但并不是实时刷新，而是用时刷新。
如果你一直让菜单保持展开状态的话，他的内容是不会更新的，下次展开菜单的就会更新了

**Comment by lihaoyun6** [comment]
@xiaobai151 
我在另一位国外用户提交的issue中看到了类似的问题. 
请问您使用的是不是基于Apple Silicon芯片的Mac?

**Comment by lihaoyun6** [comment]
@xiaobai151 
请尝试更新v0.3.3版本, 看看问题是否还会发生
