### ISSUE TITLE
How to reset trial?

### ISSUE THREAD

**Issue by melqer** [lihaoyun6/PD-Runner#143]
Hi,

PD runner working great when trial is activated. But, how to use it when Parrarels (even after fresh install) doesn't want to activate new trial on the same Mac? How to reset trial?

Best

**Comment by lihaoyun6** [comment]
@melqer 
You can find the solution here: https://github.com/lihaoyun6/PD-Runner/issues/140#issuecomment-990192031 ^_^

**Comment by melqer** [comment]
Thanks a lot mate, but this solution probably expired :/ When I change system date macOS got problem with SSL connection, even Safari won't open pages (with error SSL). The same story with Parallels: SSL connection error.

**Comment by nomecreonada** [comment]
You only have to change the date once and temporarily, once you have run a VM with PD runner, close the VM put the correct time, from there the VMs with PD runner will work without having to change the VM again date.
