### ISSUE TITLE
Should the counter of the days of the trial period change?

### ISSUE THREAD

**Issue by ErAr01** [lihaoyun6/PD-Runner#144]
Hello, I installed Parallels 17 and run it via PD, but the trial period day counter does not stop, is that how it should be?

**Comment by lihaoyun6** [comment]
@ErAr01 
PD Runner does not need to stop or modify the trial period timer.
Because what PD Runner does is to cheat PD after the trial period ends. It will make PD believe that an expired license has not expired.
