### ISSUE TITLE
Error Domain=CFErrorDomainLaunchd Code=9 "(null)"

### ISSUE THREAD

**Issue by xyange** [lihaoyun6/PD-Runner#145]
Error Domain=CFErrorDomainLaunchd Code=9 "(null)"错误怎么解决

**Comment by lihaoyun6** [comment]
@xyange 
请注意阅读README文件, 此问题的解决方法在[#常见问题](https://github.com/lihaoyun6/PD-Runner#常见问题)第4条第1款
