### ISSUE TITLE
check for Updates

### ISSUE THREAD

**Issue by puma791** [lihaoyun6/PD-Runner#148]
does not work check for updates. pd runner 0.3.3

**Comment by lihaoyun6** [comment]
@puma791 
What do you mean? Does PD Runner display any alerts?

**Comment by puma791** [comment]
I click on check for updates… no warning comes out, with previous versions yes.

**Comment by lihaoyun6** [comment]
@puma791 
Please upload the log.

**How to get logs:**
1. Right click "PD Runner. app", and then click "Show Package Contents"
2. Go to "Contents" > "MacOS" folder
3. Double click the "PD Runner" file to start PD Runner in verbose mode
4. click on "Check for Updates…"
5. Copy or screenshot the contents in the Terminal window, and then reply it to me

**Comment by puma791** [comment]
<img width="587" alt="Schermata 2021-12-11 alle 13 32 53" src="https://user-images.githubusercontent.com/95686245/145676641-76c6effb-5bba-4008-bd33-22bab1354b07.png">

**Comment by lihaoyun6** [comment]
@puma791 
Due to my mistake, the update function cannot be executed when the "Auto Update" is turned off
I'll fix it in the next version

**Comment by puma791** [comment]
ok. thanks

**Comment by lihaoyun6** [comment]
@puma791 
Fixed in v0.3.4

**Comment by puma791** [comment]
pd runner does not open if the trial version has already expired.
