### ISSUE TITLE
提个建议，还是把软件自动修改系统时间的原理写明比较好

### ISSUE THREAD

**Issue by Lezcool** [lihaoyun6/PD-Runner#15]
虽然短时间内改回来了，但是某些依赖系统时间的软件突然大量报错。
虽说不是啥大事，还是提醒下让人有个心理准备比较好。

**Comment by lihaoyun6** [comment]
啊这, 已经在README里做出说明了...
<img width="705" alt="Xnip2021-10-31_17-17-05" src="https://user-images.githubusercontent.com/16348097/139575897-a7111a3d-76f0-4f76-b707-6014622f61e1.png">

**Comment by alxt17** [comment]
非常感谢作者的无私分享！

作者说明了修改时间的原理，但我觉得，也许会有人不太了解修改时间可能会造成其他程序报错（即使是很短时间的修改）。
所以，如果可以强调说明一下（再加上举例就太好了）。这样既可以给人以心理准备，也提醒大家尽量避免在执行某些任务时使用本工具，以免某些软件报错会造成影响。

**Comment by lihaoyun6** [comment]
> 非常感谢作者的无私分享！
> 
> 作者说明了修改时间的原理，我觉得可以再强调说明一下，因为也许有人不太了解修改时间可能会造成其他程序报错（即使是很短时间的修改）。 所以，如果可以强调一下（再加上举例就太好了）。这样既可以给人以心理准备，也提醒大家尽量避免在执行某些任务时使用本工具，以免某些软件报错会造成影响。

不错的建议, 我会去更新一下README文件, 着重说一下这点.

**Comment by lihaoyun6** [comment]
那么这个issue就关闭了, 感谢您的支持与反馈
