### ISSUE TITLE
network unavailable

### ISSUE THREAD

**Issue by puma791** [lihaoyun6/PD-Runner#150]
I noticed that every time I update pd runner with a new version I no longer have the internet connection on the virtual machine, to restore it I have to go and delete the file network.desktop.xml
I noticed that it happens even when not updating pd runner.
![Immagine 2021-12-11 184834](https://user-images.githubusercontent.com/95686245/145686703-e88ee507-386f-40a4-b277-554f849cc23b.png)

**Comment by lihaoyun6** [comment]
@puma791 
😂 Maybe it's a bug in Parallels Desktop.
PD Runner doesn't change network settings.

**Comment by puma791** [comment]
Same thing happens with the cracked version of the TnT group, to make the network work you have to modify the network.desktop.xml file, exactly the UseKextless line with value 1 you have to put 0 and the network will work. On the other hand, with the trial version of parallels, the network runs smoothly.
