### ISSUE TITLE
隐藏菜单栏的图标后自动模式无法成功启动

### ISSUE THREAD

**Issue by wwenc6621** [lihaoyun6/PD-Runner#154]
菜单栏图标隐藏后，比如虚拟机暂停，点击虚拟机的启动按钮， 会弹窗

**Comment by lihaoyun6** [comment]
@wwenc6621 
好的, 我以收到. 会尽量在下个版本中修复, 感谢您的反馈.
如有任何需您配合解决的步骤, 会在此issue继续跟进. 请您持续保持关注

**Comment by lihaoyun6** [comment]
@wwenc6621 
已在v0.3.5版本中修复
