### ISSUE TITLE
Error Domain=CFErrorDomainLaunchd Code=9 "(null)"

### ISSUE THREAD

**Issue by 991567775** [lihaoyun6/PD-Runner#155]
输入命令后报错：Error Domain=CFErrorDomainLaunchd Code=9 "(null)"

**Comment by vipsunwei** [comment]
Error Domain=CFErrorDomainLaunchd Code=9 "(null)"

**Comment by lihaoyun6** [comment]
@991567775 @vipsunwei 
<img width="371" alt="Xnip2021-12-14_16-37-25" src="https://user-images.githubusercontent.com/16348097/145962794-e14dcac4-086a-45ef-8125-aeaae47fd7a2.png">
请看[这里](https://github.com/lihaoyun6/PD-Runner/blob/main/README.md#4-安装帮助程序时弹出错误提示怎么办)
