### ISSUE TITLE
Request to add a UI prompt when failed to start the VM | 请求添加在启动 VM 失败时的 UI 提示

### ISSUE THREAD

**Issue by Keldos-Li** [lihaoyun6/PD-Runner#157]
我尝试通过点击菜单栏上的按钮启动自己的虚拟机，但是什么也没有发生。打开`PD Runner.app/Contents/MacOS/PD Runner`之后得到的提示是`Failed to start the VM: There's not enough disk space available to start "Keldos’ Windows 11". Free at least 10222 MB on the hard disk that stores "Keldos’ Windows 11" and try again.` 即本机储存容量不够。
我不是很清楚是不是因为Parallels Desktop本身有提示弹窗但是被PD Runner屏蔽了。或许作者能够增加一个UI界面上的提示，避免出现用户为自己无法打开虚拟机而毫无提示感到不解。感谢作者！

I tried to start my virtual machine by clicking the button on the menu bar, but nothing happened. After opening `PD Runner.app/Contents/Mac OS/PD Runner`, the prompt I get is `Failed to start the VM: There's not enough disk space available to start "Keldos’ Windows 11". Free at least 10222 MB on the hard disk that stores "Keldos’ Windows 11" and try again.` which means the storage capacity of my mac is not enough. 
I am not sure if it is because Parallels Desktop itself has a pop-up window to tip me but it is blocked by PD Runner. Perhaps your team can add a prompt on the UI interface to prevent users from being puzzled by the fact that they cannot open the virtual machine without any prompts. Thanks a lot!

PD Runner 0.3.4 (34) / macOS Big Sur 11.6

**Comment by lihaoyun6** [comment]
@Keldos-Li 
好的, 我会考虑这样做, 感谢您的反馈
Ok, I will try to do this. Thanks for your suggestions

**Comment by lihaoyun6** [comment]
@Keldos-Li 
已在v0.3.5版本中修复
Fixed in v0.3.5 version
