### ISSUE TITLE
Can you add Catalan language to the app, please?

### ISSUE THREAD

**Issue by Austrapede** [lihaoyun6/PD-Runner#161]
Hello. I have created the file for the Catalan language of your application, if you would kindly review it and add it, I would appreciate it. Thank you very much for the application, it is great!

[ca_strings.txt](https://github.com/lihaoyun6/PD-Runner/files/7706908/ca_strings.txt)

**Comment by lihaoyun6** [comment]
@Austrapede 
Ok, I will add this Catalan translation (and your ID) in PD Runner.
Thank you for your support😄

**Comment by Austrapede** [comment]
Thanks a lot!
