### ISSUE TITLE
开启PD后，会修改Mac的时间。时间是正确的的。但是会修改星期

### ISSUE THREAD

**Issue by liujvfeng** [lihaoyun6/PD-Runner#163]

**Comment by lihaoyun6** [comment]
@liujvfeng 
PD Runner的核心运行机制就是快速修改系统时间, 并准确的在适当的时机给Parallels Desktop发送启动命令
所以启动虚拟机时发现有一瞬间系统的时间被修改了, 是正常现象, 也是无法避免的
