### ISSUE TITLE
软件在 macOS 12.1 (21C52) 无法启动

### ISSUE THREAD

**Issue by zhirongxiang** [lihaoyun6/PD-Runner#166]
最新版本在 macOS 12.1 (21C52) 正式版上无法正常启动，报错：
<img width="259" alt="image" src="https://user-images.githubusercontent.com/10797739/146094286-848c9b22-6551-4f31-93da-9e139acff429.png">
型号：MacBook Air (M1, 2020)
谢谢

**Comment by lihaoyun6** [comment]
@zhirongxiang 
从图标和警告信息上来看, 这好像不是PD Runner. 您确定您使用的是PD Runner吗?

**Comment by Patri0t-7** [comment]
你这个是奸商卖的无限启动器，请尊重作者谢谢

**Comment by zhirongxiang** [comment]
> 你这个是奸商卖的无限启动器，请尊重作者谢谢

是我搞错了。没有不尊重作者的意思，请不要随便给别人扣帽子。

**Comment by zhirongxiang** [comment]
> @zhirongxiang
> 从图标和警告信息上来看, 这好像不是PD Runner. 您确定您使用的是PD Runner吗?

是我搞错了。电脑上有两个同名的软件。抱歉。
