### ISSUE TITLE
0.3.4无法启动虚拟机，0.3.3没问题

### ISSUE THREAD

**Issue by lileixuan** [lihaoyun6/PD-Runner#167]
0.3.3使用的时候也有开率打不开虚拟机
0.3.4就是100%打不开了

是不是系统时间修改回正常了，pd还没有启动啊

原来使用的是pd17.1.0，升级到17.1.1反倒是好使了

**Comment by lihaoyun6** [comment]
@lileixuan 
请问现在是什么状况呢?  
PD Runner v0.3.4+Parallels Desktop v17.1.1组合的情况下, 是否能够正常启动虚拟机呢?

**Comment by lileixuan** [comment]
现在可以正常使用了

**Comment by lihaoyun6** [comment]
@lileixuan 
好的, 那我就关闭这条issue了.
