### ISSUE TITLE
PD Runner v0.3.4+Parallels Desktop v17.1.1 融合模式下，点击dock栏windows图标，无限跳过期警告弹窗

### ISSUE THREAD

**Issue by wangmeng1991** [lihaoyun6/PD-Runner#169]

**Comment by wangmeng1991** [comment]
点击dock栏windows图标 疯狂跳过期弹窗(十几次) 一段时间后（5分钟左右） 恢复正常

**Comment by lihaoyun6** [comment]
@wangmeng1991 
没理解究竟发生了什么. 可以详细描述一下吗

**Comment by lihaoyun6** [comment]
@wangmeng1991 
尝试复现失败. 我没有遇到类似的问题

**Comment by lihaoyun6** [comment]
@wangmeng1991 
你可以试试先关闭"屏蔽过期警告"功能, 然后看看弹出来的那些弹窗都是什么内容...

**Comment by wangmeng1991** [comment]
> @wangmeng1991 你可以试试先关闭"屏蔽过期警告"功能, 然后看看弹出来的那些弹窗都是什么内容...
我先尝试复现下

**Comment by wangmeng1991** [comment]
https://user-images.githubusercontent.com/33443928/146130757-2024e0a9-097c-4ec8-b06a-48aea052857f.mp4

**Comment by wangmeng1991** [comment]
> a7a8e763a82aaff4260dc6706b94dc9d_661240135680_v_1639547335684862.mp4

@lihaoyun6 已复现

**Comment by lihaoyun6** [comment]
@wangmeng1991 
我看pd的图标一直在启动, 但是pd关了正常win图标也会消失呀

**Comment by lihaoyun6** [comment]
@wangmeng1991  虚拟机启动了吗, 菜单栏图标是什么情况. 这些都得说清

**Comment by wangmeng1991** [comment]
> @wangmeng1991 虚拟机启动了吗, 菜单栏图标是什么情况. 这些都得说清

windows11虚拟机已启动  处于融合模式 菜单栏图标是windows11的图标

**Comment by wangmeng1991** [comment]
> @wangmeng1991 你是怎么做到只启动虚拟机而不运行pd的?

pd启动了是融合模式 ， 融合模式没有pd图标

**Comment by lihaoyun6** [comment]
@wangmeng1991 
按照您提供的信息进行了配置还原(Win11系统, 融合模式, 启动虚拟机的情况下点击dock图标)
但是我这边还是没有出现频繁弹出试用弹窗的问题... 点击dock图标之后正常弹出了win11系统的开始菜单

**Comment by wangmeng1991** [comment]
> @wangmeng1991 按照您提供的信息进行了配置还原(Win11系统, 融合模式, 启动虚拟机的情况下点击dock图标) 但是我这边还是没有出现频繁弹出试用弹窗的问题... 点击dock图标之后正常弹出了win11系统的开始菜单

这是个偶发问题 只是今天出现的比较频繁 我以后调成全屏吧

**Comment by J-seven-jp** [comment]
在融合模式下，别点击Windows图标，点击 PD Runner启动 试一下

**Comment by J-seven-jp** [comment]
如果点击PD Runner可以打开Windows系统，大概率是因为你在融合模式下的Windows正处于已暂停的状态

**Comment by wangmeng1991** [comment]
> 如果点击PD Runner可以打开Windows系统，大概率是因为你在融合模式下的Windows正处于已暂停的状态

试了下 把这个勾选去掉 恢复正常了
![image](https://user-images.githubusercontent.com/33443928/146167779-39a4dca3-32f4-49e0-b92a-3bb103e79ab0.png)

**Comment by lihaoyun6** [comment]
问题已解决, 故关闭此issue
