### ISSUE TITLE
请教个问题 PDST.scpt 是做什么的呢

### ISSUE THREAD

**Issue by qisikai** [lihaoyun6/PD-Runner#17]
hi， 首先感谢大佬的无私奉献，最近对这个启动器很感兴趣， 阅读代码发现有一个文件 “PDST.scpt”
1.  请教一下这个脚本的作用是？ 2. 我打开看着是一个binary， 请教下这个文件是怎么生成的呢

**Comment by hlgsdx** [comment]
It's a compiled script created with Apple's Script Editor. Simply run `osadecompile file` to decompile it.
```
$ osadecompile PDST.scpt
set PD to "Parallels Desktop"
set PDA to application PD
repeat while true
	if PDA is running then
		if PD is in (get name of every window of PDA) then
			repeat 4 times
				tell PDA to close (every window whose name is PD)
				delay 0.1
			end repeat
		end if
	end if
	delay 1
end repeat
```

**Comment by lihaoyun6** [comment]
> hi， 首先感谢大佬的无私奉献，最近对这个启动器很感兴趣， 阅读代码发现有一个文件 “PDST.scpt”
> 
> 1. 请教一下这个脚本的作用是？ 2. 我打开看着是一个binary， 请教下这个文件是怎么生成的呢

1. 这个脚本是用于实现"屏蔽促销弹窗"功能的. 当开启此功能时PD Runner会在后台运行此脚本, 脚本的作用是定时检测所有Parallels Desktop程序打开的窗口, 如果检测到其中有提示试用过期的窗口则将其自动关闭.
2. 这个脚本并没有"加密", 使用macOS自带的"脚本编辑器"即可打开. 之所以是个二进制文件, 是因为"脚本编辑器"在保存的时候会自动编译.
