### ISSUE TITLE
磁盘空间不足时使用PD Runner启动会导致空间不足提示不显示

### ISSUE THREAD

**Issue by SunDaydream** [lihaoyun6/PD-Runner#171]
在磁盘空间不足时使用PD Runner启动会导致空间不足提示不显示

**Comment by lihaoyun6** [comment]
> 在磁盘空间不足时使用PD Runner启动会导致空间不足提示不显示

会在下个版本中加入对虚拟机启动失败原因的提示弹窗

**Comment by lihaoyun6** [comment]
v0.3.5版本已发布
