### ISSUE TITLE
Trail out of data

### ISSUE THREAD

**Issue by Azjmeng** [lihaoyun6/PD-Runner#175]
I had got a PD trial for 14 days, and now I have no trial for PD. When I first run the PD-runner It says that I must get a trial of Parallel Desktop
![image](https://user-images.githubusercontent.com/46107027/146382196-ec6a7d46-f461-412e-a504-d13b6e625dbd.png)
How can I fix this issue

**Comment by jimococo** [comment]
You can set the date to a day that has not passed the trial period，then restart the parallels desktop application , the "trial" button which you can press will appear. Press the "trial" button and run your virtual machine normally once。now you can use the pd runner without any problems.
