### ISSUE TITLE
能不强制更新吗？

### ISSUE THREAD

**Issue by EggsBlue** [lihaoyun6/PD-Runner#178]
给小白同事装上了，但是经常更新，每次更新都要跳转github，他还访问不了。能手动更新吗 或不强制更新也可使用

**Comment by jimococo** [comment]
可以去macwk网站更新，非常推荐这个网站，站长良心。

**Comment by Liujishou** [comment]
https://gitee.com/lihaoyun/PD-Runner 国内同步更新
https://gitee.com/lihaoyun/PD-Runner/tree/main/release

**Comment by lihaoyun6** [comment]
> 给小白同事装上了，但是经常更新，每次更新都要跳转github，他还访问不了。能手动更新吗 或不强制更新也可使用
<img width="327" alt="Xnip2021-12-21_15-44-53" src="https://user-images.githubusercontent.com/16348097/146891040-8d78bc38-f5cf-4500-a873-67c78d9c66d5.png">
