### ISSUE TITLE
启动PD Runner提示未注册试用期！请先在Parallels Desktop中注册试用期 然后即可使用PD Runner来启动虚拟机 (试用期过后依然有效)。无法启动启动器

### ISSUE THREAD

**Issue by xis666** [lihaoyun6/PD-Runner#179]

**Comment by jinglianqi** [comment]
把系统时间改成 2021 年 9 月 1 号或者改成在你试用期内的日期，然后运行 PD，弹出试用窗口的时候点击「继续试用」，然后把 PD 退出，系统时间改回来，再用启动器启动即可。

**Comment by xis666** [comment]
> 

感谢，问题解决

**Comment by samgump** [comment]
> 把系统时间改成 2021 年 9 月 1 号或者改成在你试用期内的日期，然后运行 PD，弹出试用窗口的时候点击「继续试用」，然后把 PD 退出，系统时间改回来，再用启动器启动即可。

完全无效果
