### ISSUE TITLE
0.1.12版安裝問題

### ISSUE THREAD

**Issue by digitalhouse** [lihaoyun6/PD-Runner#18]
今天安裝0.1.12版後無法執行，一直跳出以下錯誤視窗，後來移除舊版重新安裝後正常
<img width="362" alt="截圖 2021-11-01 10 39 53" src="https://user-images.githubusercontent.com/786348/139614864-417f0355-05d8-42b1-805a-067d23512f76.png">

**Comment by lihaoyun6** [comment]
您说的"後來移除舊版重新安裝後正常"指的是?
是指卸载0.1.12, 然后安装旧版的可以正常使用
还是彻底移除旧版之后再安装0.1.12可以正常使用?

**Comment by digitalhouse** [comment]
> 您說的"後來移除舊版重新安裝後正常"指的是? 是指卸載0.1.12, 然後安裝舊版的可以正常使用 還是徹底移除舊版之後再安裝0.1.12可以正常使用?

我是直接用App Cleaner & Uninstaller整個移除安裝後再重新安裝0.1.12版，本來安裝的是0.1.10版，但是沒有移除，直接把0.1.12拉到應用程式執行安裝，打開就出現上面錯誤。現在0.1.12版使用正常

**Comment by lihaoyun6** [comment]
> > 您說的"後來移除舊版重新安裝後正常"指的是? 是指卸載0.1.12, 然後安裝舊版的可以正常使用 還是徹底移除舊版之後再安裝0.1.12可以正常使用?
> 
> 我是直接用App Cleaner & Uninstaller整個移除安裝後再重新安裝0.1.12版，本來安裝的是0.1.10版，但是沒有移除，直接把0.1.12拉到應用程式執行安裝，打開就出現上面錯誤。現在0.1.12版使用正常

已经查明原因了, 因为我不是苹果的付费开发者, 所以我是用的是临时开发者证书.
我的证书这几天过期了, 签名0.1.12所用的证书和旧版不同, 所以在覆盖安装Helper程式的时候, macOS会认为是另一个恶意程序在进行注入攻击, 所以就会这样.
彻底卸载旧版是一个合适的方法, 我也将上传一个清除旧版环境的脚本, 方便大家使用
感谢您的反馈
