### ISSUE TITLE
PD-Runner启动虚拟机时，会改变屏幕色温

### ISSUE THREAD

**Issue by me450722457** [lihaoyun6/PD-Runner#182]
OS version：12.1 (21C52)
PD-Runner version：0.3.5 (35)

启动虚拟机时，会改变屏幕色温，看上去像是突然打开了“夜览”后再关闭的过程。

**Comment by Wongboo** [comment]
改时间导致的吧

**Comment by me450722457** [comment]
> 改时间导致的吧

应该是的，我的夜览设定是“日落到日出”，但是之前版本没发现启动虚拟机屏幕会变色
