### ISSUE TITLE
打开屏蔽过期警告时会导致“系统事件”CPU使用长期保持在10%左右

### ISSUE THREAD

**Issue by wuhelong** [lihaoyun6/PD-Runner#184]
打开屏蔽过期警告时会导致“系统事件”CPU使用长期保持在10%左右
系统信息：
macOS 12.0.1 
MacBook Pro (15-inch, 2018)

谢谢

**Comment by lihaoyun6** [comment]
@wuhelong 
因为PD Runner需要实时监控PD是否有弹窗动作. 而为了保证及时关闭弹窗, 监控频率设置的比较高(每秒5次) 
所以在某些CPU性能不高的Mac上可能就会表现为长期存在一个固定的性能占用. 
目前暂时没有更好的解决方法, 如果担心性能占用, 可以考虑暂时关闭这项功能.
