### ISSUE TITLE
parallels desktop无法恢复快照

### ISSUE THREAD

**Issue by xiebruce** [lihaoyun6/PD-Runner#19]
parallels desktop无法恢复快照，一恢复就弹出购买界面

**Comment by KevinLiu1995** [comment]
+1

**Comment by xiebruce** [comment]
> +1

我现在的办法是先修改系统时间（修改成距离你安装pd的时间的14天内，也就是pd试用还没过期的那个时间），然后再关掉pd，然后直接运行pd（不用pd启动器），运行pd后，就可以恢复快照了。

**Comment by lihaoyun6** [comment]
好的, 我会对这个问题进行调试, 看看是否能够解决

**Comment by lihaoyun6** [comment]
@xiebruce @KevinLiu1995 
请更新v0.2.0, 新版PD Runner已经加入了对于"恢复快照"功能的支持. 不要再手动改时间了, 可以一键完成

**Comment by KevinLiu1995** [comment]
> @xiebruce @KevinLiu1995 请更新v0.2.0, 新版PD Runner已经加入了对于"恢复快照"功能的支持. 不要再手动改时间了, 可以一键完成

Nice
