### ISSUE TITLE
咱们的工具是可以无视parallels的更新吗？

### ISSUE THREAD

**Issue by devilpie** [lihaoyun6/PD-Runner#193]
你好，paralles提示更新，不敢更新，查看readme，没有找到工具最新可以对应什么版本。想问下是可以对应所有版本？

**Comment by lihaoyun6** [comment]
@devilpie 目前从17.0.1到最新的17.1.1都经过测试可以兼容. 正常更新至最新版也不会失效的

**Comment by devilpie** [comment]
谢谢老大
