### ISSUE TITLE
17.2版本的有计划么大佬

### ISSUE THREAD

**Issue by 10628913** [lihaoyun6/PD-Runner#197]

**Comment by lihaoyun6** [comment]
@10628913 PD官网还没有退出17.2更新, 不知道您是从那里看到的

**Comment by 10628913** [comment]
我从appstore 下的

**Comment by lihaoyun6** [comment]
@10628913 
PD Runner不对Apple Store版的Parallels Desktop提供支持.
仅支持官网下载的版本
