### ISSUE TITLE
“屏蔽促销弹窗”疑似造成macOS下触摸板单击及按压无反应

### ISSUE THREAD

**Issue by aizhimoran** [lihaoyun6/PD-Runner#2]
mac系统版本：12.0.1
PD版本：17.1.0
虚拟机win版本：win11
PD Runner版本：0.1.8
“屏蔽促销弹窗”疑似造成macOS下触摸板单击及按压无反应，各手势及双指单击正常，大约启动虚拟机后2min会出现该现象，killall Dock无改善，只能重启解决。取消勾选后测试10min未复现，触摸板一切正常。

**Comment by lihaoyun6** [comment]
经过长时间测试与多方收集, 暂时未发现遇到同样情况的用户. 因为无法复现, 所以不知道是不是普遍问题, 也不确定该如何解决.
故此暂时关闭此issue, 给您带来的不便十分抱歉
