### ISSUE TITLE
请教该程序 最低Mac运行版本？

### ISSUE THREAD

**Issue by FAST0888** [lihaoyun6/PD-Runner#20]

**Comment by lihaoyun6** [comment]
目前本项目设置的编译目标为macOS 10.15

**Comment by FAST0888** [comment]
能不能支持一下10.13.6 麻烦了

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 83992713** [comment]
应用程序“PD Runner”的这个版本不能与此版本的 macOS 配合使用。您使用的是 macOS 10.14.6。该应用程序要求 macOS 10.15 或更高版本。

老铁能否忙不支持下Mojave

**Comment by libopenggggg** [comment]
> > 应用程序“PD Runner”的这个版本不能与此版本的 macOS 配合使用。您使用的是 macOS 10.14.6。该应用程序要求 macOS 10.15 或更高版本。
> 
> > 
> 
> > 老铁能否忙不支持下Mojave
> 
> 
> 
> 版本这么低的 mac os。直接可以 搜 tnt 破解版本的 pd 吧 ，完整破解版 的   

tnt 破解软件一般哪里发布 有网站吗

**Comment by digit77com** [comment]
> > > 应用程序“PD Runner”的这个版本不能与此版本的 macOS 配合使用。您使用的是 macOS 10.14.6。该应用程序要求 macOS 10.15 或更高版本。
> > 
> > 
> > > 
> > 
> > 
> > > 老铁能否忙不支持下Mojave
> > 
> > 
> > 版本这么低的 mac os。直接可以 搜 tnt 破解版本的 pd 吧 ，完整破解版 的
> 
> tnt 破解软件一般哪里发布 有网站吗

https://www.digit77.com/
https://www.minorpatch.com/

完全免费

**Comment by JowayYoung** [comment]
@lihaoyun6 老哥，我安装了PD Runder和PD，使用PD Runder点击启动无任何反应，是什么回事呢？10.15.7的系统

**Comment by Minxio** [comment]
打不开软件，系统10.15.7

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue
