### ISSUE TITLE
有人非法收费下载

### ISSUE THREAD

**Issue by webstorm-dxy** [lihaoyun6/PD-Runner#21]
你好，开发者，有人非法使用你的pdrunner进行收费下载操作，希望你能够去处理，地址：http://www.jbzy.cn/803.html

**Comment by lihaoyun6** [comment]
![B12525F2E8FDD1813968C50D93998705](https://user-images.githubusercontent.com/16348097/139708664-dd2f81e1-b223-443d-a23d-61d6e4daf35f.jpg)
已经向网站上预留的客服QQ提出了严正声明. 并将在下个版本中加入警示弹窗. 感谢您的反馈与支持

**Comment by lihaoyun6** [comment]
经过交涉已解决此问题, 故关闭此issue, 感谢您的支持与提醒.

**Comment by Cubik65536** [comment]
提醒一下，该链接仍然有效，不知道是否仍然可以购买或者获取下载
