### ISSUE TITLE
GitHub上只有源码  APP过着dmg的包怎么下载

### ISSUE THREAD

**Issue by 790902750** [lihaoyun6/PD-Runner#22]
GitHub上只有源码  APP过着dmg的包怎么下载  谢谢

**Comment by lihaoyun6** [comment]
点击此处可跳转到最新的预构建版本下载 (国内用户下载需要科学上网)
<img width="1252" alt="Xnip2021-11-02_00-30-10" src="https://user-images.githubusercontent.com/16348097/139706403-a5bbc68c-19ad-4b1c-adaf-e888aa163e3d.png">

**Comment by lihaoyun6** [comment]
国内用户可以去[https://www.macwk.com/soft/pd-runner](https://www.macwk.com/soft/pd-runner)这里下载. 
这是国内的一个完全免费的mac软件分享网站, 我授权站长转发分流PD Runner, 以方便无法科学上网的朋友下载使用.
网站上的更新可能会比github慢一天左右, 已经算是很及时了.
