### ISSUE TITLE
最新的monterey 12.1Beta打不开…

### ISSUE THREAD

**Issue by guokai10000** [lihaoyun6/PD-Runner#23]
升级了最新的12.1Beta，还因此换了新的6600XT显卡，但是最新的0.012启动器打不开…

**Comment by junheming** [comment]
the same as you～

**Comment by digitalhouse** [comment]
這應該跟12.1沒關係，我的M1 MBP 用12.1Beta完全沒問題

**Comment by lihaoyun6** [comment]
本人不对任何测试版系统中发现的软件使用问题负责, 故关闭此issue
