### ISSUE TITLE
运行PD Runner之后，顶部菜单上未出现运行的图标

### ISSUE THREAD

**Issue by winstudio-nt** [lihaoyun6/PD-Runner#25]
活动监视器里能看到这 PD Runner  已经运行了的，请大家帮忙找解决办法

**Comment by Ajiade** [comment]
同样的问题。启用开机启动功能，偶尔开机看不到图标，进系统活动监控器看是程序未响应。

**Comment by lihaoyun6** [comment]
> 同样的问题。启用开机启动功能，偶尔开机看不到图标，进系统活动监控器看是程序未响应。

先关闭PD Runner. 然后右键点击PD Runner app, 选择"显示包内容"
之后依次进入Contents > MacOS, 双击其中的PD Runner可执行文件
之后PD Runner会以调试模式运行, 请按照您平常的使用过程操作一下
之后把弹出窗口中的日志截图或复制发上来, 以便我定位问题, 谢谢

**Comment by CarterLi** [comment]
我也出现了同样的问题，时好时不好

感觉是系统bug

**Comment by winstudio-nt** [comment]
> > 同样的问题。启用开机启动功能，偶尔开机看不到图标，进系统活动监控器看是程序未响应。
> 
> 先关闭PD Runner. 然后右键点击PD Runner app, 选择"显示包内容" 之后依次进入Contents > MacOS, 双击其中的PD Runner可执行文件 之后PD Runner会以调试模式运行, 请按照您平常的使用过程操作一下 之后把弹出窗口中的日志截图或复制发上来, 以便我定位问题, 谢谢

是我的问题，已经解决。我用了hidden bar和低分辨率模式，顶部菜单显示不全，造成无法看到pd runner的图标。后切换到最高分辨率及暂停hidden bar，就看到这pd runner的图标了，，目前正常使用。

**Comment by lihaoyun6** [comment]
> > > 同样的问题。启用开机启动功能，偶尔开机看不到图标，进系统活动监控器看是程序未响应。
> 
> > 
> 
> > 先关闭PD Runner. 然后右键点击PD Runner app, 选择"显示包内容" 之后依次进入Contents > MacOS, 双击其中的PD Runner可执行文件 之后PD Runner会以调试模式运行, 请按照您平常的使用过程操作一下 之后把弹出窗口中的日志截图或复制发上来, 以便我定位问题, 谢谢
> 
> 
> 
> 是我的问题，已经解决。我用了hidden bar和低分辨率模式，顶部菜单显示不全，造成无法看到pd runner的图标。后切换到最高分辨率及暂停hidden bar，就看到这pd runner的图标了，，目前正常使用。

好的，祝您使用愉快。那我就先关闭这个issue了
