### ISSUE TITLE
能够启动，出现顶部菜单，但是选择windows 10不能启动，也没有报错

### ISSUE THREAD

**Issue by nmweizi** [lihaoyun6/PD-Runner#26]
0.1.12，macos 11.6
能够启动，出现顶部菜单，但是选择windows 10后虚拟机没有启动，也没有报错

**Comment by lihaoyun6** [comment]
先关闭PD Runner. 然后右键点击PD Runner app, 选择"显示包内容"
之后依次进入Contents > MacOS, 双击其中的PD Runner可执行文件
之后PD Runner会以调试模式运行, 请按照您平常的使用过程操作一下
之后把弹出窗口中的日志截图或复制发上来, 以便我定位问题, 谢谢

**Comment by smilingpoplar** [comment]
同样，0.1.12, 0.2.0都只能调出pd控制中心，无法启动虚拟机

<img width="561" alt="截屏2021-11-03 09 32 27" src="https://user-images.githubusercontent.com/219728/139996124-9125d7ad-6ee3-4732-a740-1d0721b7be52.png">

**Comment by level1807** [comment]
I have a similar problem, here's the full output

`2021-11-03 18:45:16.8160 Check helper status...
2021-11-03 18:45:16.8170 Helper installed.
2021-11-03 18:45:16.8380 Installed version: 0.1.12, InBundle version: 0.1.12
2021-11-03 18:45:16.8390 Helper installed.
2021-11-03 18:45:22.9910 VM list: [Windows 10 Mojave:win-10]
2021-11-03 18:45:22.9950 Run PDST...
2021-11-03 18:45:22.9990 Run loop...
2021-11-03 18:45:43.1060 Starting VM: Windows 10 Mojave
2021-11-03 18:45:43.1180 Launching Parallels Desktop...
2021-11-03 18:45:45.4390 Time-
2011-11-06 17:45:45.1910 The command is available only in Parallels Desktop for Mac Pro or Business Edition.
2011-11-06 17:45:45.1910 Skipping Pro/Business Edition detection...
2011-11-06 17:45:45.2570 Time+
2021-11-03 18:45:49.7920 Time-
Nov  6 17:46:22  pdfm-bootstrap[30005] <Error>: prlctl[29712]: Dispather last try output: Login failed: Unable to connect to Parallels Service. Make sure that the prl_disp_service process is active and it is not blocked by Firewall. For details, please refer to this knowledgebase article (https://www.parallels.com/products/desktop/supportinfo/pdfm17_en_US_249).
Nov  6 17:46:22  pdfm-bootstrap[30006] <Error>: prlctl[29712]: Failed to initialize Parallels Desktop in unattended mode.
	This may be caused by ether corrupt installation or if you just installed Parallels Desktop.
	In order to initialize Parallels desktop ether:
	1. Start Paralles Desktop by double-clicking to Parallels Desktop bundle, or
	2. Run following initialization procedure from command line:
	sudo "/Applications/Parallels Desktop.app/Contents/MacOS/inittool2" init -b "/Applications/Parallels Desktop.app"
2011-11-06 17:46:22.4560 Time+`

**Comment by lihaoyun6** [comment]
> I have a similar problem, here's the full output. At the end of the process the VM window is open but clicking the "play" button only flashes the login popup for a moment, nothing happens after that.
> 
> 
> 
> ```
> 
> 2021-11-03 18:45:16.8160 Check helper status...
> 
> 2021-11-03 18:45:16.8170 Helper installed.
> 
> 2021-11-03 18:45:16.8380 Installed version: 0.1.12, InBundle version: 0.1.12
> 
> 2021-11-03 18:45:16.8390 Helper installed.
> 
> 2021-11-03 18:45:22.9910 VM list: [Windows 10 Mojave:win-10]
> 
> 2021-11-03 18:45:22.9950 Run PDST...
> 
> 2021-11-03 18:45:22.9990 Run loop...
> 
> 2021-11-03 18:45:43.1060 Starting VM: Windows 10 Mojave
> 
> 2021-11-03 18:45:43.1180 Launching Parallels Desktop...
> 
> 2021-11-03 18:45:45.4390 Time-
> 
> 2011-11-06 17:45:45.1910 The command is available only in Parallels Desktop for Mac Pro or Business Edition.
> 
> 2011-11-06 17:45:45.1910 Skipping Pro/Business Edition detection...
> 
> 2011-11-06 17:45:45.2570 Time+
> 
> 2021-11-03 18:45:49.7920 Time-
> 
> Nov  6 17:46:22  pdfm-bootstrap[30005] <Error>: prlctl[29712]: Dispather last try output: Login failed: Unable to connect to Parallels Service. Make sure that the prl_disp_service process is active and it is not blocked by Firewall. For details, please refer to this knowledgebase article (https://www.parallels.com/products/desktop/supportinfo/pdfm17_en_US_249).
> 
> Nov  6 17:46:22  pdfm-bootstrap[30006] <Error>: prlctl[29712]: Failed to initialize Parallels Desktop in unattended mode.
> 
> 	This may be caused by ether corrupt installation or if you just installed Parallels Desktop.
> 
> 	In order to initialize Parallels desktop ether:
> 
> 	1. Start Paralles Desktop by double-clicking to Parallels Desktop bundle, or
> 
> 	2. Run following initialization procedure from command line:
> 
> 	sudo "/Applications/Parallels Desktop.app/Contents/MacOS/inittool2" init -b "/Applications/Parallels Desktop.app"
> 
> 2011-11-06 17:46:22.4560 Time+
> 
> ```

Have you tried to restart your Mac and try again？

**Comment by lihaoyun6** [comment]
> 同样，0.1.12, 0.2.0都只能调出pd控制中心，无法启动虚拟机
> 
> 
> 
> <img width="561" alt="截屏2021-11-03 09 32 27" src="https://user-images.githubusercontent.com/219728/139996124-9125d7ad-6ee3-4732-a740-1d0721b7be52.png">
> 
> 

看起来是Helper没有正常工作，修改系统时间没成功，可以尝试用release里面的Uninstall-Helper清楚一下运行环境，然后再打开PD Runner试试

**Comment by smilingpoplar** [comment]
> > 同样，0.1.12, 0.2.0都只能调出pd控制中心，无法启动虚拟机
> > <img alt="截屏2021-11-03 09 32 27" width="561" src="https://user-images.githubusercontent.com/219728/139996124-9125d7ad-6ee3-4732-a740-1d0721b7be52.png">
> 
> 看起来是Helper没有正常工作，修改系统时间没成功，可以尝试用release里面的Uninstall-Helper清楚一下运行环境，然后再打开PD Runner试试

运行Uninstall-Helper后可以正常启动了

**Comment by smilingpoplar** [comment]
用Uninstall-Helper后可以启动了

lihaoyun6 ***@***.***>于2021年11月4日 周四10:03写道：

**Comment by nmweizi** [comment]
使用Uninstall-Helper搞定

**Comment by redduckyy** [comment]
Where to download? Got link?

**Comment by redduckyy** [comment]
What is the password?

acBook-Air ~ % sudo launchctl enable system/com.lihaoyun6.PD-Runner-Helper

Password:

**Comment by nmweizi** [comment]
@redduckyy 
https://github.com/lihaoyun6/PD-Runner/releases/download/0.2.0/Uninstall-Helper.zip

**Comment by redduckyy** [comment]
Thank you!!

Downloaded the file. How do I run it?
