### ISSUE TITLE
PD Runner打开以后显示试用期油3000多天，这个正常吗？

### ISSUE THREAD

**Issue by J-seven-jp** [lihaoyun6/PD-Runner#27]
PD Runner打开以后显示试用期油3000多天，可以正常使用，这个是显示问题嘛
![02cc2696dc7023d6b566fc2207a79d4](https://user-images.githubusercontent.com/93599046/139866906-75fe907c-9d45-41e5-a765-8d45cbc55499.jpg)

**Comment by lihaoyun6** [comment]
1. PD Runner能不能正常启动虚拟机?
2. 启动虚拟机后, macOS的系统时间会错乱吗?

**Comment by J-seven-jp** [comment]
1.PD Runner可以正常启动虚拟机，只是弹窗显示3000多天，
2.启动虚拟机后, macOS的系统时间无任何变化，一切正常。

因为现在还在试用期内，所以把系统时间往后修改了一个月，打开正常PD提示过试用期需要购买，在过期的状态下打开PD Runner可以正常启动虚拟机，且弹窗显示正常。

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue
