### ISSUE TITLE
安装后menubar有图标，点击虚拟机启动之后pd会闪退，然后等待几秒后弹出如下弹窗

### ISSUE THREAD

**Issue by goxofy** [lihaoyun6/PD-Runner#29]
![image](https://user-images.githubusercontent.com/1695416/140002931-40eb681e-15a2-41e2-a44e-62f96f4b0157.png)

**Comment by Ajiade** [comment]
你pd安装好还没运行一下吧。运行一下，还得授权。再去使用启动器就没问题了。

**Comment by goxofy** [comment]
@Ajiade 运行过了啊，有三台虚拟机，只不过现在直接在pd里面点虚拟机的话会弹出输入许可证，但是我的试用许可证已经过期了，这怎么办

**Comment by lihaoyun6** [comment]
> @Ajiade 运行过了啊，有三台虚拟机，只不过现在直接在pd里面点虚拟机的话会弹出输入许可证，但是我的试用许可证已经过期了，这怎么办

遇到这个弹窗可以先尝试重启一下macOS，然后再试试启动虚拟机

**Comment by goxofy** [comment]
@lihaoyun6 谢谢，我重新安装了一次pd就ok了

**Comment by lihaoyun6** [comment]
因为PD17.1.0引入了新的使用权鉴定措施，所以切换系统时间是绕过激活的一个重要步骤。而切换系统时间的时机非常重要，不能太早也不能太晚。有的时候确实是会导致PD服务运行失败，这也是PD的反制措施之一。
所以我在更新日志里经常说的一句话是"提高了虚拟机启动的成功率"，并不能保证100%每次都成功启动。能力有限，抱歉😢
