### ISSUE TITLE
0.2问题多多哈

### ISSUE THREAD

**Issue by maoqoo** [lihaoyun6/PD-Runner#30]
感谢提供免费软件，0.2问题有点多，mac和pd虚拟机win11端时间都显示为2031年，mac端pd过期弹窗，无法关机，已换回0.1.12
提个小建议：可不可以加入mac关机，pd直接关机功能，目前是恢复win11，恢复后的日期为2011年，过一会儿显示正常

**Comment by lihaoyun6** [comment]
因为PD17.1.0引入了新的使用权鉴定措施，所以切换系统时间是必不可少的一个步骤。只要不是每次都会导致macOS和虚拟机时间长期错乱，就属于正常现象。
除非是每次启动虚拟机后macOS和虚拟机的时间都会错乱，而且短时间内没有办法自动复原，这种是属于异常现象。

**Comment by lihaoyun6** [comment]
@maoqoo 
v0.2.1以更新, 完全改变了时间计算方法. 理论上来说应该是能够修复时间错乱的问题. 可以更新试试

**Comment by devilyard** [comment]
> @maoqoo
> v0.2.1以更新, 完全改变了时间计算方法. 理论上来说应该是能够修复时间错乱的问题. 可以更新试试

不知道为什么0.2.1更新后程序很卡，第一次打开后，点击状态栏的图标很久都没有反应，过了有10几秒吧，弹出菜单，后面每次点击都要1秒左右才出来菜单

**Comment by lihaoyun6** [comment]
> > @maoqoo
> > v0.2.1以更新, 完全改变了时间计算方法. 理论上来说应该是能够修复时间错乱的问题. 可以更新试试
> 
> 不知道为什么0.2.1更新后程序很卡，第一次打开后，点击状态栏的图标很久都没有反应，过了有10几秒吧，弹出菜单，后面每次点击都要1秒左右才出来菜单

是我修改了菜单的刷新方式. 有点激进了.没有考虑到prlctl命令执行会阻塞主线程. 抱歉, 下个版本再优化一下

**Comment by YoungYuan1971** [comment]
感谢软件作者！v0.2.1启动PD时，会显示到期提示画面，但一闪而过。v0.2.0没有此状况。

**Comment by Ajiade** [comment]
> > > @maoqoo
> > > v0.2.1以更新, 完全改变了时间计算方法. 理论上来说应该是能够修复时间错乱的问题. 可以更新试试
> > 
> > 
> > 不知道为什么0.2.1更新后程序很卡，第一次打开后，点击状态栏的图标很久都没有反应，过了有10几秒吧，弹出菜单，后面每次点击都要1秒左右才出来菜单
> 
> 是我修改了菜单的刷新方式. 有点激进了.没有考虑到prlctl命令执行会阻塞主线程. 抱歉, 下个版本再优化一下

0.2.2版本第一次点击图标也要等很久

**Comment by lihaoyun6** [comment]
> > > > @maoqoo
> > > > v0.2.1以更新, 完全改变了时间计算方法. 理论上来说应该是能够修复时间错乱的问题. 可以更新试试
> > > 
> > > 
> > > 不知道为什么0.2.1更新后程序很卡，第一次打开后，点击状态栏的图标很久都没有反应，过了有10几秒吧，弹出菜单，后面每次点击都要1秒左右才出来菜单
> > 
> > 
> > 是我修改了菜单的刷新方式. 有点激进了.没有考虑到prlctl命令执行会阻塞主线程. 抱歉, 下个版本再优化一下
> 
> 0.2.2版本第一次点击图标也要等很久

现在再试试呢

**Comment by Ajiade** [comment]
貌似没问题了👍
