### ISSUE TITLE
不知道和新版PD软件有关系没用 突然MAC系统崩溃！

### ISSUE THREAD

**Issue by hzmnet** [lihaoyun6/PD-Runner#32]

**Comment by Bald-youth** [comment]
我的版本是big sur11.2 昨天也出现了一次开机问题，不知道是否影响系统稳定性。

**Comment by hzmnet** [comment]
我是装新版本PD17.10开始出现的各种异常。这次崩溃表现为Luncher花屏 然后关闭所有运行的MAC 程序，然后直接显示登陆画面。系统没有重启！

**Comment by lihaoyun6** [comment]
我在开发和使用的过程中暂时没有遇到类似问题。不过macOS 12系统目前还不是十分稳定，在使用的过程确实又可能出现意料之外的异常情况。
并非我作为作者不愿意承认问题， 而是确实暂时没有足够的证据支撑确认为是PD Runner导致的系统崩溃。
感谢您的支持

**Comment by hzmnet** [comment]
嗯！ 现在装会老版本PD测试 ！

**Comment by lihaoyun6** [comment]
长时间未回复, 故结束此issue. 
如发现其他问题, 可另行提交
