### ISSUE TITLE
对于加密状态的虚拟机系统，虽然pd runner有提示密码输入框，但正确输入密码后并没有自动打开虚拟机系统

### ISSUE THREAD

**Issue by KyoShio** [lihaoyun6/PD-Runner#34]
![image](https://user-images.githubusercontent.com/20240090/140064772-03cafe23-d0a0-444c-b19c-cce3fd7206df.png)
![image](https://user-images.githubusercontent.com/20240090/140064802-cb0d0958-bd7a-4fce-988e-64c1c64a16eb.png)
输完pd runne的密码框就一直停在这了

**Comment by lihaoyun6** [comment]
从日志上来看，这个虚拟机确实是启动成功了。但为什么没有显示虚拟机窗口，这个我再排查一下吧

**Comment by lihaoyun6** [comment]
> ![image](https://user-images.githubusercontent.com/20240090/140064772-03cafe23-d0a0-444c-b19c-cce3fd7206df.png)
> ![image](https://user-images.githubusercontent.com/20240090/140064802-cb0d0958-bd7a-4fce-988e-64c1c64a16eb.png)
> 输完pd runne的密码框就一直停在这了

已经查明问题了，这是 parallels desktop本身的一个bug。我正在寻求有没有解决的方法，不过我不能保证什么…

**Comment by lihaoyun6** [comment]
@KyoShio 
这个问题已经"基本上"解决了, 新版PD Runner可以在开机后强制弹出系统窗口.
只是加密虚拟机开机之后需要用户手动操作一下才能显示系统画面. 我会在新版PD Runner中加入弹窗指导用户操作

**Comment by KyoShio** [comment]
> 画面

2..0版本可以吗？还是要下一个版本

**Comment by lihaoyun6** [comment]
> > 画面
> 
> 0.2版本可以吗？还是说要下一个版本？

要0.2.1版本了, 预计今晚更新

**Comment by KyoShio** [comment]
> > > 画面
> > 
> > 
> > 0.2版本可以吗？还是说要下一个版本？
> 
> 要0.2.1版本了, 预计今晚更新

好的 感谢！
