### ISSUE TITLE
无法启动虚拟机

### ISSUE THREAD

**Issue by ChuanfengZhang** [lihaoyun6/PD-Runner#36]
重启、使用 Uninstall-Helper、重装 PD 都试过了，麻烦帮忙看看是什么原因🤔
<img width="652" alt="image" src="https://user-images.githubusercontent.com/18238800/140284306-19492973-770f-4e85-abfb-1908599e9ec6.png">

**Comment by lihaoyun6** [comment]
> 重启、使用 Uninstall-Helper、重装 PD 都试过了，麻烦帮忙看看是什么原因🤔
> <img alt="image" width="652" src="https://user-images.githubusercontent.com/18238800/140284306-19492973-770f-4e85-abfb-1908599e9ec6.png">

根据我这个月以来的调试经验, 重启macOS然后重装一下Parallels Desktop应该就解决了

**Comment by macbloke** [comment]
> > 重启、使用 Uninstall-Helper、重装 PD 都试过了，麻烦帮忙看看是什么原因🤔
> > <img alt="image" width="652" src="https://user-images.githubusercontent.com/18238800/140284306-19492973-770f-4e85-abfb-1908599e9ec6.png">
> 
> 根据我这个月以来的调试经验, 重启macOS然后重装一下Parallels Desktop应该就解决了


還是不行
0.2.2更出現prl_disp_service崩潰

**Comment by lihaoyun6** [comment]
@ChuanfengZhang @macbloke 
请问两位开过试用吗? 必须要先在PD里面开始14天试用, 启动器才能生效. 不然的话巧妇也难为无米之炊

**Comment by lihaoyun6** [comment]
毕竟这个软件的作用是"绕过试用过期警告", 而不是凭空变出使用时长...

**Comment by LLLgoyour** [comment]
同问题

**Comment by lihaoyun6** [comment]
> 同问题

请问开始过试用吗，需要先开始试用然后才能用启动器（试用过期没事，但没开始过试用是不行的）

**Comment by ChuanfengZhang** [comment]
> @ChuanfengZhang @macbloke
> 请问两位开过试用吗? 必须要先在PD里面开始14天试用, 启动器才能生效. 不然的话巧妇也难为无米之炊.
> 毕竟这个软件的作用是"绕过试用过期警告", 而不是凭空变出使用时长... 所以需要先开始试用, 先打破从0到1才行

啊我之前没试用😅刚登录账号后发现还有试用期，用启动器也成功启动了。

**Comment by LLLgoyour** [comment]
> > 同问题
> 
> 请问开始过试用吗，需要先开始试用然后才能用启动器（试用过期没事，但没开始过试用是不行的）

使用过期已经过了 但是我的是即使打开了窗口也没有运行
