### ISSUE TITLE
自动打开VMware fusion怎么处理

### ISSUE THREAD

**Issue by sabosanbosocho** [lihaoyun6/PD-Runner#37]
我这里pd和VMware都装了，用pd runner启动pd虚拟机，虽然pd虚拟机正常启动了，但同时也会自动打开vmware，怎么解决？

**Comment by jack89zhao** [comment]
same issue

**Comment by lihaoyun6** [comment]
> 我这里pd和VMware都装了，用pd runner启动pd虚拟机，虽然pd虚拟机正常启动了，但同时也会自动打开vmware，怎么解决？

请问是0.2.1版本出现的问题吗

**Comment by lihaoyun6** [comment]
> 我这里pd和VMware都装了，用pd runner启动pd虚拟机，虽然pd虚拟机正常启动了，但同时也会自动打开vmware，怎么解决？

已经复现并定位到问题了, 是由于vmware对于PD的".pvm"虚拟机包文件的强制关联导致的. 会在下个版本中修复

**Comment by lihaoyun6** [comment]
> same issue

OK, this bug will be fixed in v0.2.2

**Comment by xfqz86** [comment]
出现同样的问题，等待0.2.2修复😴

**Comment by lihaoyun6** [comment]
> 出现同样的问题，等待0.2.2修复😴

已经发布了新的release, 可以去更新了
