### ISSUE TITLE
关于封闭源代码

### ISSUE THREAD

**Issue by Cubik65536** [lihaoyun6/PD-Runner#38]
非常感谢作者提供了这样的工具！我非常理解由于被非法售卖而进行闭源。但是我仍然希望能够或许到源代码，因为我希望我授予系统管理权限的软件能够更加透明，至少大部分可以。我相信 GitHub 也有部分的用户希望可以这样。所以，不知道作者是否愿意通过 Private Repo 和较为严格的邀请措施来向仍然希望获得源代码的用户和其他开发者开源。

感谢！

**Comment by bao3** [comment]
想获取源代码？如何保证获取源代码后的行为。。。。。？

**Comment by Cubik65536** [comment]
无所谓了… 本意是希望可以让自己运行的软件更受到自己的控制。如果无法建立信任也只能表示理解。
