### ISSUE TITLE
Monterey 下启动不了，闪退

### ISSUE THREAD

**Issue by cong8341** [lihaoyun6/PD-Runner#4]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               PD Runner [65047]
Path:                  /Applications/PD Runner.app/Contents/MacOS/PD Runner
Identifier:            com.lihaoyun6.PD-Runner
Version:               0.1.9 (???)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-10-28 10:57:14.7375 +0800
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        D32F09B9-845C-8615-A186-6244C699C72B

Sleep/Wake UUID:       C0A49DC1-E004-4538-83C2-66CD6FB7BF4C

Time Awake Since Boot: 5100 seconds
Time Since Wake:       1122 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [65047]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   PD Runner                     	       0x102175c70 AppDelegate.constructMenu() + 4160
1   PD Runner                     	       0x10217265d AppDelegate.applicationDidFinishLaunching(_:) + 349
2   PD Runner                     	       0x1021727ba @objc AppDelegate.applicationDidFinishLaunching(_:) + 106
3   CoreFoundation                	    0x7ff80f020e73 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
4   CoreFoundation                	    0x7ff80f0be349 ___CFXRegistrationPost_block_invoke + 49
5   CoreFoundation                	    0x7ff80f0be2c6 _CFXRegistrationPost + 496
6   CoreFoundation                	    0x7ff80eff2786 _CFXNotificationPost + 733
7   Foundation                    	    0x7ff80fe3a996 -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
8   AppKit                        	    0x7ff811a5d18b -[NSApplication _postDidFinishNotification] + 305
9   AppKit                        	    0x7ff811a5cedd -[NSApplication _sendFinishLaunchingNotification] + 208
10  AppKit                        	    0x7ff811a5aab0 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541
11  AppKit                        	    0x7ff811a5a707 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665
12  Foundation                    	    0x7ff80fe66284 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
13  Foundation                    	    0x7ff80fe660f6 _NSAppleEventManagerGenericHandler + 80
14  AE                            	    0x7ff8156a7d28 0x7ff81569c000 + 48424
15  AE                            	    0x7ff8156a7592 0x7ff81569c000 + 46482
16  AE                            	    0x7ff8156a09c7 aeProcessAppleEvent + 419
17  HIToolbox                     	    0x7ff817c58b42 AEProcessAppleEvent + 54
18  AppKit                        	    0x7ff811a54d8a _DPSNextEvent + 2064
19  AppKit                        	    0x7ff811a52f5c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1411
20  AppKit                        	    0x7ff811a45359 -[NSApplication run] + 586
21  AppKit                        	    0x7ff811a191f8 NSApplicationMain + 816
22  PD Runner                     	       0x102176809 main + 9
23  dyld                          	       0x1031214fe start + 462

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff80ef6000c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff80ef6000c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff80ef6000c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	    0x7ff80ef6000c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff80ef6000c start_wqthread + 0

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff80ef27aba mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80ef27e2b mach_msg + 59
2   CoreFoundation                	    0x7ff80f02ba42 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff80f02a11b __CFRunLoopRun + 1325
4   CoreFoundation                	    0x7ff80f02952d CFRunLoopRunSpecific + 563
5   AppKit                        	    0x7ff811bc2cec _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff80ef64514 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff80ef6002f thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000600002ea7660  rbx: 0x00006000035ee2f8  rcx: 0x0000000000000001  rdx: 0x0000000000000004
  rdi: 0xc00000000000000a  rsi: 0x40006000020f8200  rbp: 0x00007ff7bdd91210  rsp: 0x00007ff7bdd91140
   r8: 0x0000000000000057   r9: 0x000000000000000a  r10: 0x0000000000000004  r11: 0x00007ff80f013def
  r12: 0x40006000020f8200  r13: 0xe300000000000000  r14: 0x0000000000000001  r15: 0x0000000000000002
  rip: 0x0000000102175c70  rfl: 0x0000000000010246  cr2: 0x00000001021751a0
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     6

Thread 0 instruction stream:
  48 89 df 48 8b 1d ce 74-00 00 ff d3 4c 89 ff ff  H..H...t....L...
  d3 4c 89 f7 ff d3 48 8b-05 4b ce 00 00 48 8b 4d  .L....H..K...H.M
  c8 48 8b 3c 01 4a 8b 14-29 48 8b 35 30 bf 00 00  .H.<.J..)H.50...
  e8 21 47 00 00 48 8b bd-70 ff ff ff e8 75 47 00  .!G..H..p....uG.
  00 48 8b bd 68 ff ff ff-48 81 c4 a8 00 00 00 5b  .H..h...H......[
  41 5c 41 5d 41 5e 41 5f-5d e9 58 47 00 00 0f 0b  A\A]A^A_].XG....
 [0f]0b 0f 0b 0f 0b 0f 0b-0f 0b 66 0f 1f 44 00 00  ..........f..D..	<==
  55 48 89 e5 41 57 41 56-41 55 41 54 53 50 49 89  UH..AWAVAUATSPI.
  d7 49 89 fc 48 89 d7 e8-6e 45 00 00 49 89 c5 49  .I..H...nE..I..I
  89 d6 48 8d 3d 2f ce 00-00 e8 a2 0b 00 00 be 40  ..H.=/.........@
  00 00 00 ba 07 00 00 00-48 89 c7 e8 f4 46 00 00  ........H....F..
  48 89 c3 0f 28 05 d6 4b-00 00 0f 11 40 10 48 8b  H...(..K....@.H.

Binary Images:
       0x10216d000 -        0x10217cfff com.lihaoyun6.PD-Runner (0.1.9) <cefd6a62-3e68-3f42-88f5-2980a1e2f2fe> /Applications/PD Runner.app/Contents/MacOS/PD Runner
    0x7ff80efab000 -     0x7ff80f4adfff com.apple.CoreFoundation (6.9) <3002b545-6841-3fc8-91a2-bcfbe5872465> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff80fe31000 -     0x7ff8101ebfff com.apple.Foundation (6.9) <d7fd0214-4bbb-3d84-88f7-820b25a6e16c> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff811a16000 -     0x7ff8128a2fff com.apple.AppKit (6.9) <dd0028a3-78e3-3a8a-a51b-ddd68123adef> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff81569c000 -     0x7ff815709fff com.apple.AE (924) <c6abf4fe-9c8d-368a-9361-20d89338fe42> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7ff817c18000 -     0x7ff817f0ffff com.apple.HIToolbox (2.1.1) <4163a93f-bf71-3219-80ed-6f65e9266b81> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x10311c000 -        0x103187fff dyld (*) <1a6ae033-9438-33c0-8077-988fd885250a> /usr/lib/dyld
    0x7ff80ef5e000 -     0x7ff80ef69fff libsystem_pthread.dylib (*) <29a2750e-f31b-3630-8761-242a6bc3e99e> /usr/lib/system/libsystem_pthread.dylib
    0x7ff80ef27000 -     0x7ff80ef5dfff libsystem_kernel.dylib (*) <12bd6f13-c452-35ee-9069-51befef29f1a> /usr/lib/system/libsystem_kernel.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=953.7M resident=0K(0%) swapped_out_or_unallocated=953.7M(100%)
Writable regions: Total=609.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=609.7M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          212K       23 
CoreGraphics                        12K        2 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           214.4M       40 
MALLOC guard page                   32K        8 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        7 
Stack                             11.0M        7 
VM_ALLOCATE                         40K        8 
__DATA                            21.3M      372 
__DATA_CONST                      19.7M      235 
__DATA_DIRTY                      1141K      146 
__FONT_DATA                          4K        1 
__LINKEDIT                       635.8M       10 
__OBJC_RO                         81.5M        1 
__OBJC_RW                         3120K        2 
__TEXT                           317.9M      391 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                      131.8M       15 
shared memory                      772K       16 
===========                     =======  ======= 
TOTAL                              1.8G     1290 
TOTAL, minus reserved VM space     1.5G     1290 

-----------
Full Report
-----------

{"app_name":"PD Runner","timestamp":"2021-10-28 10:57:14.00 +0800","app_version":"0.1.9","slice_uuid":"cefd6a62-3e68-3f42-88f5-2980a1e2f2fe","build_version":"","platform":1,"bundleID":"com.lihaoyun6.PD-Runner","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"EE90CB22-8F1D-40B5-95E5-2A43678FE69D","name":"PD Runner"}
{
  "uptime" : 5100,
  "procLaunch" : "2021-10-28 10:57:14.2286 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro13,3",
  "procStartAbsTime" : 5158356587635,
  "coalitionID" : 1778,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-10-28 10:57:14.7375 +0800",
  "incident" : "EE90CB22-8F1D-40B5-95E5-2A43678FE69D",
  "bug_type" : "309",
  "pid" : 65047,
  "procExitAbsTime" : 5158864542185,
  "cpuType" : "X86-64",
  "procName" : "PD Runner",
  "procPath" : "\/Applications\/PD Runner.app\/Contents\/MacOS\/PD Runner",
  "bundleInfo" : {"CFBundleShortVersionString":"0.1.9","CFBundleIdentifier":"com.lihaoyun6.PD-Runner"},
  "storeInfo" : {"deviceIdentifierForVendor":"507D1A4C-7C1A-506F-B2D6-2E3B8F14BD99","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.lihaoyun6.PD-Runner",
  "crashReporterKey" : "D32F09B9-845C-8615-A186-6244C699C72B",
  "wakeTime" : 1122,
  "bridgeVersion" : {"build":"14Y908","train":"3.0"},
  "sleepWakeUUID" : "C0A49DC1-E004-4538-83C2-66CD6FB7BF4C",
  "sip" : "disabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_INSTRUCTION","signal":"SIGILL"},
  "termination" : {"flags":0,"code":4,"namespace":"SIGNAL","indicator":"Illegal instruction: 4","byProc":"exc handler","byPid":65047},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":214515,"instructionState":{"instructionStream":{"bytes":[72,137,223,72,139,29,206,116,0,0,255,211,76,137,255,255,211,76,137,247,255,211,72,139,5,75,206,0,0,72,139,77,200,72,139,60,1,74,139,20,41,72,139,53,48,191,0,0,232,33,71,0,0,72,139,189,112,255,255,255,232,117,71,0,0,72,139,189,104,255,255,255,72,129,196,168,0,0,0,91,65,92,65,93,65,94,65,95,93,233,88,71,0,0,15,11,15,11,15,11,15,11,15,11,15,11,102,15,31,68,0,0,85,72,137,229,65,87,65,86,65,85,65,84,83,80,73,137,215,73,137,252,72,137,215,232,110,69,0,0,73,137,197,73,137,214,72,141,61,47,206,0,0,232,162,11,0,0,190,64,0,0,0,186,7,0,0,0,72,137,199,232,244,70,0,0,72,137,195,15,40,5,214,75,0,0,15,17,64,16,72,139],"offset":96}},"threadState":{"r13":{"value":16357073846609641472},"rax":{"value":105553165186656},"rflags":{"value":66118},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":4611791571578225152},"r8":{"value":87},"cr2":{"value":4330049952},"rdx":{"value":4},"r10":{"value":4},"r9":{"value":10},"r15":{"value":2},"rbx":{"value":105553172816632},"trap":{"value":6},"err":{"value":0},"r11":{"value":140703380356591,"symbolLocation":0,"symbol":"-[__NSCFString _fastCStringContents:]"},"rip":{"value":4330052720,"matchesCrashFrame":1},"rbp":{"value":140702018769424},"rsp":{"value":140702018769216},"r12":{"value":4611791571578225152},"rcx":{"value":1},"flavor":"x86_THREAD_STATE","rdi":{"value":13835058055282163722}},"queue":"com.apple.main-thread","frames":[{"imageOffset":35952,"symbol":"AppDelegate.constructMenu()","symbolLocation":4160,"imageIndex":0},{"imageOffset":22109,"symbol":"AppDelegate.applicationDidFinishLaunching(_:)","symbolLocation":349,"imageIndex":0},{"imageOffset":22458,"symbol":"@objc AppDelegate.applicationDidFinishLaunching(_:)","symbolLocation":106,"imageIndex":0},{"imageOffset":482931,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":12,"imageIndex":1},{"imageOffset":1127241,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":49,"imageIndex":1},{"imageOffset":1127110,"symbol":"_CFXRegistrationPost","symbolLocation":496,"imageIndex":1},{"imageOffset":292742,"symbol":"_CFXNotificationPost","symbolLocation":733,"imageIndex":1},{"imageOffset":39318,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":82,"imageIndex":2},{"imageOffset":291211,"symbol":"-[NSApplication _postDidFinishNotification]","symbolLocation":305,"imageIndex":3},{"imageOffset":290525,"symbol":"-[NSApplication _sendFinishLaunchingNotification]","symbolLocation":208,"imageIndex":3},{"imageOffset":281264,"symbol":"-[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:]","symbolLocation":541,"imageIndex":3},{"imageOffset":280327,"symbol":"-[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:]","symbolLocation":665,"imageIndex":3},{"imageOffset":217732,"symbol":"-[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:]","symbolLocation":308,"imageIndex":2},{"imageOffset":217334,"symbol":"_NSAppleEventManagerGenericHandler","symbolLocation":80,"imageIndex":2},{"imageOffset":48424,"imageIndex":4},{"imageOffset":46482,"imageIndex":4},{"imageOffset":18887,"symbol":"aeProcessAppleEvent","symbolLocation":419,"imageIndex":4},{"imageOffset":265026,"symbol":"AEProcessAppleEvent","symbolLocation":54,"imageIndex":5},{"imageOffset":257418,"symbol":"_DPSNextEvent","symbolLocation":2064,"imageIndex":3},{"imageOffset":249692,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1411,"imageIndex":3},{"imageOffset":193369,"symbol":"-[NSApplication run]","symbolLocation":586,"imageIndex":3},{"imageOffset":12792,"symbol":"NSApplicationMain","symbolLocation":816,"imageIndex":3},{"imageOffset":38921,"symbol":"main","symbolLocation":9,"imageIndex":0},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":6}]},{"id":214520,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":214521,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":214531,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":214532,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":214543,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":214596,"name":"com.apple.NSEventThread","frames":[{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":8},{"imageOffset":3627,"symbol":"mach_msg","symbolLocation":59,"imageIndex":8},{"imageOffset":526914,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":520475,"symbol":"__CFRunLoopRun","symbolLocation":1325,"imageIndex":1},{"imageOffset":517421,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":1},{"imageOffset":1756396,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":3},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4330016768,
    "CFBundleShortVersionString" : "0.1.9",
    "CFBundleIdentifier" : "com.lihaoyun6.PD-Runner",
    "size" : 65536,
    "uuid" : "cefd6a62-3e68-3f42-88f5-2980a1e2f2fe",
    "path" : "\/Applications\/PD Runner.app\/Contents\/MacOS\/PD Runner",
    "name" : "PD Runner"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703379927040,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "3002b545-6841-3fc8-91a2-bcfbe5872465",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1855.105"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703395155968,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 3911680,
    "uuid" : "d7fd0214-4bbb-3d84-88f7-820b25a6e16c",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1855.105"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703424405504,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15257600,
    "uuid" : "dd0028a3-78e3-3a8a-a51b-ddd68123adef",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703487868928,
    "CFBundleShortVersionString" : "924",
    "CFBundleIdentifier" : "com.apple.AE",
    "size" : 450560,
    "uuid" : "c6abf4fe-9c8d-368a-9361-20d89338fe42",
    "path" : "\/System\/Library\/Frameworks\/CoreServices.framework\/Versions\/A\/Frameworks\/AE.framework\/Versions\/A\/AE",
    "name" : "AE",
    "CFBundleVersion" : "924"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703527174144,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3112960,
    "uuid" : "4163a93f-bf71-3219-80ed-6f65e9266b81",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4346462208,
    "size" : 442368,
    "uuid" : "1a6ae033-9438-33c0-8077-988fd885250a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703379611648,
    "size" : 49152,
    "uuid" : "29a2750e-f31b-3630-8761-242a6bc3e99e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703379386368,
    "size" : 225280,
    "uuid" : "12bd6f13-c452-35ee-9069-51befef29f1a",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703376384000,
  "size" : 15213641728,
  "uuid" : "3d05845f-3f65-358f-9ebf-2236e772ac01"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=953.7M resident=0K(0%) swapped_out_or_unallocated=953.7M(100%)\nWritable regions: Total=609.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=609.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          212K       23 \nCoreGraphics                        12K        2 \nFoundation                          16K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           214.4M       40 \nMALLOC guard page                   32K        8 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        7 \nStack                             11.0M        7 \nVM_ALLOCATE                         40K        8 \n__DATA                            21.3M      372 \n__DATA_CONST                      19.7M      235 \n__DATA_DIRTY                      1141K      146 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       635.8M       10 \n__OBJC_RO                         81.5M        1 \n__OBJC_RW                         3120K        2 \n__TEXT                           317.9M      391 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                      131.8M       15 \nshared memory                      772K       16 \n===========                     =======  ======= \nTOTAL                              1.8G     1290 \nTOTAL, minus reserved VM space     1.5G     1290 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61704e71b6f6b8421579caf8"
      },
      "deploymentId" : 240000293
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000145
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000064
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6169fcad436117010456880e"
      },
      "deploymentId" : 240000238
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by lihaoyun6** [comment]
@cong8341  
更新了v0.1.11, 已经修复了, 可以尝试下载使用看看
