### ISSUE TITLE
建议加入自动更新功能

### ISSUE THREAD

**Issue by xfqz86** [lihaoyun6/PD-Runner#40]
建议作者加入自动更新功能，每次都需要到github下载有些许麻烦

**Comment by lihaoyun6** [comment]
> 建议作者加入自动更新功能，每次都需要到github下载有些许麻烦

自动更新需要维护更新服务器, 比较麻烦

**Comment by xfqz86** [comment]
> > 建议作者加入自动更新功能，每次都需要到github下载有些许麻烦
> 
> 自动更新需要维护更新服务器, 比较麻烦

貌似可以基于 GitHub Release 自动更新，只是个建议，如果非常麻烦的话还是我手工下载吧😂

**Comment by xfqz86** [comment]
提供一个参考示例：https://github.com/yanue/V2rayU/blob/master/V2rayU/MainMenu.swift

**Comment by lihaoyun6** [comment]
> > > 建议作者加入自动更新功能，每次都需要到github下载有些许麻烦
> > 
> > 
> > 自动更新需要维护更新服务器, 比较麻烦
> 
> 貌似可以基于 GitHub Release 自动更新，只是个建议，如果非常麻烦的话还是我手工下载吧😂

但是还要考虑到可访问性的问题. v2rayU本身就是个科学上网软件, 所以它可以假定它的使用者都是可以正常访问github的release服务器的. 所以可以放心的使用github来做对象存储. 但是PD Runner的用户不一定都能正常访问github, 可能被墙

**Comment by xfqz86** [comment]
> 但是还要考虑到可访问性的问题. v2rayU本身就是个科学上网软件, 所以它可以假定它的使用者都是可以正常访问github的release服务器的. 所以可以放心的使用github来做对象存储. 但是PD Runner的用户不一定都能正常访问github, 可能被墙

可以尝试使用国内的 gitee

**Comment by cddehsy** [comment]
可以提示更新，然后打开网盘下载也可以啊

**Comment by lihaoyun6** [comment]
@xfqz86 @cddehsy 
加入了一个"检查更新..."按钮以供用户手动检测更新
