### ISSUE TITLE
无法打开win11镜像，ubuntu的倒是可以

### ISSUE THREAD

**Issue by wloverine** [lihaoyun6/PD-Runner#43]

**Comment by wloverine** [comment]
pd-runner版本：0.2.2

**Comment by lihaoyun6** [comment]
> pd-runner版本：0.2.2

更新0.2.3试试

**Comment by macbloke** [comment]
更新0.2.3, 付費窗口沒有出現, parallels is starting 然後閃退

**Comment by macbloke** [comment]
> 更新0.2.3, 付費窗口沒有出現, parallels is starting 然後閃退

原來是根本沒有開始試用

**Comment by wloverine** [comment]
> > 更新0.2.3, 付費窗口沒有出現, parallels is starting 然後閃退
> 
> 原來是根本沒有開始試用

我的也是，window 11镜像加载完了一直卡在单击继续
<img width="872" alt="image" src="https://user-images.githubusercontent.com/33534430/140614557-c766e1e9-8016-4566-b27a-501323569c5d.png">

**Comment by lihaoyun6** [comment]
> > > 更新0.2.3, 付費窗口沒有出現, parallels is starting 然後閃退
> > 
> > 
> > 原來是根本沒有開始試用
> 
> 我的也是，window 11镜像加载完了一直卡在单击继续 <img alt="image" width="872" src="https://user-images.githubusercontent.com/33534430/140614557-c766e1e9-8016-4566-b27a-501323569c5d.png">

这个不是启动器的问题哦. 在新建虚拟机的时候一定要记得勾选窗口左下角的"手动安装操作系统". 如果不勾选的话就会卡在这过不去

**Comment by wloverine** [comment]
> 

这一步过去了，但是安装完的win11没法上网了
