### ISSUE TITLE
PD17.1版本安装完系统"点击以继续"提示试用

### ISSUE THREAD

**Issue by lxf-lxf** [lihaoyun6/PD-Runner#45]
PD17.1版本安装完系统"点击以继续"
![image](https://user-images.githubusercontent.com/61101384/140699437-50da3b8f-dbbd-4eaf-a1aa-3fded0666ce7.png)
每次点击的时候都会出现试用窗口一闪而过，系统操也操作不了。

**Comment by lihaoyun6** [comment]
@lxf-lxf 创建虚拟机的时候注意勾选左下角的"手动安装操作系统". 如果不勾选的话, 就会卡在这
