### ISSUE TITLE
增加挂载已存在VM及创建新VM功能

### ISSUE THREAD

**Issue by tiggerzhang** [lihaoyun6/PD-Runner#47]
是不是考虑增加打开已存在的VM及创建新VM功能

**Comment by lihaoyun6** [comment]
> 是不是考虑增加打开已存在的VM及创建新VM功能

PD并没有在试用过期状态下限制这些功能的使用. 即使你的PD已经过了试用期, 还是可以正常的导入或者创建虚拟机. 所以直接用PD原生功能操作就好了
