### ISSUE TITLE
在新款的MacBook pro 14英寸 系统是12.1 无法打开软件

### ISSUE THREAD

**Issue by xiaobai151** [lihaoyun6/PD-Runner#48]
在系统进程中发现Pdrunner程序在运行，但是在菜单栏中并无显示

**Comment by PassXml** [comment]
你是怎么启动的Pdrunner的呢

**Comment by xiaobai151** [comment]
双击打开啊

**Comment by PassXml** [comment]
> 双击打开啊

哦哦哦..那可能真的是程序问题..之前我在用户-里面启动项-勾选了隐藏...也是会出现已经运行了,没菜单的情况...

**Comment by qiang81020** [comment]
12.0.1也无法启动了

**Comment by qiang81020** [comment]
> 12.0.1也无法启动了

下载最新的版本正常使用了

**Comment by lihaoyun6** [comment]
本人不对任何测试版系统中发现的软件使用问题负责, 故关闭此issue
