### ISSUE TITLE
点击启动PD Runner 报错

### ISSUE THREAD

**Issue by rookie-zz** [lihaoyun6/PD-Runner#51]
<img width="689" alt="截屏2021-11-11 下午3 44 24" src="https://user-images.githubusercontent.com/56228759/141258590-70beec72-895e-44b4-9a57-9d1c4f1c5480.png">

**Comment by lihaoyun6** [comment]
在"安全性与隐私"中开启"任何来源"就行了

**Comment by rookie-zz** [comment]
> 在"安全性与隐私"中开启"任何来源"就行了

我是打开的  把访达里的一个文件删掉就好了
