### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by rainto** [lihaoyun6/PD-Runner#53]
有注册提示，绕不过。。

**Comment by Liujishou** [comment]
是需要登陆pd呀  没登陆是无法启动的，注册会送14天的试用  之后使用程序绕过

**Comment by evenyip** [comment]
首先感谢作者，这款启动器比之前的用过的好用，不需要改虚拟机名称这些。
但是今天发现没办法进入虚拟机了，提醒过期页可以被屏蔽，但是百分比跑完以后卡在那里了。
