### ISSUE TITLE
未安装Parallels Desktop

### ISSUE THREAD

**Issue by zhutaofei** [lihaoyun6/PD-Runner#54]
启动之后提示未安装Parallels Desktop
![image](https://user-images.githubusercontent.com/13133912/141879076-26f80b29-4318-45e6-99cf-ce3c10828a38.png)
实际上已安装，如下图
![image](https://user-images.githubusercontent.com/13133912/141879215-3055b64d-fc49-4b89-8f28-82b867780439.png)

**Comment by zhutaofei** [comment]
> 启动之后提示未安装Parallels Desktop ![image](https://user-images.githubusercontent.com/13133912/141879076-26f80b29-4318-45e6-99cf-ce3c10828a38.png) 实际上已安装，如下图 ![image](https://user-images.githubusercontent.com/13133912/141879215-3055b64d-fc49-4b89-8f28-82b867780439.png)

补充下版本：Parallels Desktop17.1.0，PD Runner 0.2.5 (0.2.5)

**Comment by tim-huang** [comment]
在terminal 下进入/usr/local/bin, 执行sudo ln -s /Applications/Parallels\ Desktop.app/Contents/MacOS/prlctl prlctl试试看
会要求输入密码

**Comment by zhutaofei** [comment]
> 在terminal 下执行以下命令试试看
> 
> ```shell
> cd /usr/local/bin
> sudo ln -s /Applications/Parallels\ Desktop.app/Contents/MacOS/prlctl prlctl
> ```
> 
> 会要求输入密码

not a directory: /usr/local/bin  系统macOS Big Sur 11.4，M1芯片
直接配置了环境变量也未能解决

**Comment by tim-huang** [comment]
```shell
mkdir -p /usr/local/bin
cd /usr/local/bin
sudo ln -s /Applications/Parallels\ Desktop.app/Contents/MacOS/prlctl prlctl
```
我的就是这样解决的

**Comment by lihaoyun6** [comment]
> 启动之后提示未安装Parallels Desktop
> ![image](https://user-images.githubusercontent.com/13133912/141879076-26f80b29-4318-45e6-99cf-ce3c10828a38.png)
> 实际上已安装，如下图
> ![image](https://user-images.githubusercontent.com/13133912/141879215-3055b64d-fc49-4b89-8f28-82b867780439.png)

重装一下PD试试. 目前是从/usr/local/bin来索引prlctl可执行文件并以此判断PD是否安装  
下个版本我改成从绝对位置来调用吧...

**Comment by lihaoyun6** [comment]
> ```shell
> ```shell
> mkdir -p /usr/local/bin
> cd /usr/local/bin
> sudo ln -s /Applications/Parallels\ Desktop.app/Contents/MacOS/prlctl prlctl
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 我的就是这样解决的
> ```

不要随便去link, 你这个实际上是错误操作
/usr/local/bin/prlctl并非指向/Applications/Parallels Desktop.app/Contents/MacOS/prlctl
而是指向/Applications/Parallels Desktop.app/Contents/MacOS/parallels_wrapper的一个软链接

**Comment by lihaoyun6** [comment]
@tim-huang 不要随便去link, 你这个实际上是错误操作
/usr/local/bin/prlctl 并非指向 /Applications/Parallels Desktop.app/Contents/MacOS/prlctl
而是指向 /Applications/Parallels Desktop.app/Contents/MacOS/parallels_wrapper 的一个软链接

**Comment by tim-huang** [comment]
> @tim-huang 不要随便去link, 你这个实际上是错误操作
> /usr/local/bin/prlctl 并非指向 /Applications/Parallels Desktop.app/Contents/MacOS/prlctl
> 而是指向 /Applications/Parallels Desktop.app/Contents/MacOS/parallels_wrapper 的一个软链接
> wrapper会检测Parallels服务的状态, 如果服务没有正常工作的话, wrapper会进行kick up操作来重启Parallels服务
> 如果只是单纯的链接到/Applications/Parallels Desktop.app/Contents/MacOS/prlctl的话, 有时就会出现服务起不来, 显示"未安装"的情况

谢谢提醒。我对此并没有深入研究，依稀记得是升级homebrew时删除了老版本homebrew安装的内容，可能误删了/usr/local/bin下的prlctl。随后发现pd内有这个就直接链过来了，即便没有预先打开pd的情况下，pd-runner也能主动唤醒pd运行得很好。目前也不打算折腾了，期待更新你的新版本来完善它。

**Comment by gvory** [comment]
I am also having the same problem. I couldn't translate the words. Do you mind if I manually(click in applications)  to open parallels with pd turned on for now? I don't have to pay anything, do I?

**Comment by zhutaofei** [comment]
> > 启动之后提示未安装Parallels Desktop
> > ![image](https://user-images.githubusercontent.com/13133912/141879076-26f80b29-4318-45e6-99cf-ce3c10828a38.png)
> > 实际上已安装，如下图
> > ![image](https://user-images.githubusercontent.com/13133912/141879215-3055b64d-fc49-4b89-8f28-82b867780439.png)
> 
> 重装一下PD试试. 目前是从/usr/local/bin来索引prlctl可执行文件并以此判断PD是否安装 下个版本我改成从绝对位置来调用吧...

好的，等下个版本，我这应该是之前homebrew安装的问题，导致usr/local/bin是一个文件

**Comment by zhutaofei** [comment]
> > > 启动之后提示未安装Parallels Desktop
> > > ![image](https://user-images.githubusercontent.com/13133912/141879076-26f80b29-4318-45e6-99cf-ce3c10828a38.png)
> > > 实际上已安装，如下图
> > > ![image](https://user-images.githubusercontent.com/13133912/141879215-3055b64d-fc49-4b89-8f28-82b867780439.png)
> > 
> > 
> > 重装一下PD试试. 目前是从/usr/local/bin来索引prlctl可执行文件并以此判断PD是否安装 下个版本我改成从绝对位置来调用吧...
> 
> 好的，等下个版本，我这应该是之前homebrew安装的问题，导致usr/local/bin是一个文件

安装了0.2.6版本，但是出现另外的问题，连不上服务器
![image](https://user-images.githubusercontent.com/13133912/142565562-bc7ed234-8ab4-4a7b-9e90-cba20f8035a5.png)

**Comment by lihaoyun6** [comment]
> > > > 启动之后提示未安装Parallels Desktop
> > > > ![image](https://user-images.githubusercontent.com/13133912/141879076-26f80b29-4318-45e6-99cf-ce3c10828a38.png)
> > > > 实际上已安装，如下图
> > > > ![image](https://user-images.githubusercontent.com/13133912/141879215-3055b64d-fc49-4b89-8f28-82b867780439.png)
> > > 
> > > 
> > > 重装一下PD试试. 目前是从/usr/local/bin来索引prlctl可执行文件并以此判断PD是否安装 下个版本我改成从绝对位置来调用吧...
> > 
> > 
> > 好的，等下个版本，我这应该是之前homebrew安装的问题，导致usr/local/bin是一个文件
> 
> @lihaoyun6 安装了0.2.6版本，但是出现另外的问题，连不上服务 ![image](https://user-images.githubusercontent.com/13133912/142565562-bc7ed234-8ab4-4a7b-9e90-cba20f8035a5.png)

请尝试在终端执行下列命令, 并将运行截图回复上来, 谢谢
`/usr/local/bin/prlctl list -ao name,ostemplate -s mac`

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue
