### ISSUE TITLE
有试用过期提示，登录不了window

### ISSUE THREAD

**Issue by bobsafrica** [lihaoyun6/PD-Runner#57]
有注册过期提示，登录不了window

**Comment by lihaoyun6** [comment]
请附上更详细的描述或问题截图

**Comment by bobsafrica** [comment]
用PD-RUNNER启动的时候，显示 已经过了试用期，需要激活parallel才可以使用

lihaoyun6 ***@***.***> 于2021年11月17日周三 下午1:26写道：

**Comment by lihaoyun6** [comment]
> 用PD-RUNNER启动的时候，显示 已经过了试用期，需要激活parallel才可以使用 lihaoyun6 ***@***.***> 于2021年11月17日周三 下午1:26写道：
> […](#)

可以方便贴一下运行日志吗. 获取日志的方法为:
右键单击PD Runner的文件, 选择"显示包内容". 然后依次进入Contents > MacOS目录并双击其中的"PD Runner"文件
启动后尝试去复现一下刚刚的操作, 然后把弹出窗口中的日志信息复制或截图发上来就可以了

**Comment by wingkin** [comment]
请问，已经过期的情况下，可以使用该软件来启动吗？
发现上述情况下，自己一直都显示提示自己使用期限已经到期。

**Comment by lihaoyun6** [comment]
> 请问，已经过期的情况下，可以使用该软件来启动吗？
> 发现上述情况下，自己一直都显示提示自己使用期限已经到期。

试用期过期不影响PD Runner的使用. 但是一定要注意, 即使已经过期, 也不要退出Parallels Desktop账号.

**Comment by wingkin** [comment]
> 

感谢您的迅速回复。不好意思没有把问题描述清楚。

2个月以前，无账号的情况下免费使用了parallels 17。之后过期后删除了软件。

今天重新安装了parallels17，然后安装了win11. 
之后win11显示【安装完成，需要单击以继续。】
此时就会弹出试用期已经过期的窗口，并且无法继续进行下一步操作。

利用PD Runner也同样出现类似的情况。
刚刚重新注册的一个账号，同样提示已经过期。
不知道是否可以用办法解决。谢谢。

**Comment by lihaoyun6** [comment]
> 感谢您的迅速回复。不好意思没有把问题描述清楚。
> 
> 2个月以前，无账号的情况下免费使用了parallels 17。之后过期后删除了软件。
> 
> 今天重新安装了parallels17，然后安装了win11. 之后win11显示【安装完成，需要单击以继续。】 此时就会弹出试用期已经过期的窗口，并且无法继续进行下一步操作。
> 
> 利用PD Runner也同样出现类似的情况。 刚刚重新注册的一个账号，同样提示已经过期。 不知道是否可以用办法解决。谢谢。

这个不是启动器的问题, 而是创建虚拟机的时候没有设置好
在创建虚拟机的时候一定要注意观察并勾选窗口左下角的"手动安装操作系统"
如果不勾选此选项的话, 就会导致你遇到的那种情况(系统安装完成, 但是卡在最后一步无法继续)

使用正确的方法创建好虚拟机之后, 在用PD Runner启动此虚拟机, 并手动安装系统之后就可以正常使用了

**Comment by wingkin** [comment]
> 这个不是启动器的问题, 而是创建虚拟机的时候没有设置好
在创建虚拟机的时候一定要注意观察并勾选窗口左下角的"手动安装操作系统"
如果不勾选此选项的话, 就会导致你遇到的那种情况(系统安装完成, 但是卡在最后一步无法继续)
> 
> 使用正确的方法创建好虚拟机之后, 在用PD Runner启动此虚拟机, 并手动安装系统之后就可以正常使用了

太感谢您的指点了。顺利完成了安装！

**Comment by NorwayLuo** [comment]
![image](https://user-images.githubusercontent.com/49739715/142746182-27b939a6-e1af-4a36-8ee5-81bf0df82f8d.png)

**Comment by lihaoyun6** [comment]
> ![image](https://user-images.githubusercontent.com/49739715/142746182-27b939a6-e1af-4a36-8ee5-81bf0df82f8d.png)
> 
> 

First you need to log in to your Parallels Desktop account, then get a 14-day free trial. 
And you should never log out of your account even after the trial expires!
