### ISSUE TITLE
macOS Mojave 10.14 non compatible

### ISSUE THREAD

**Issue by ceipi** [lihaoyun6/PD-Runner#58]
Great work. Thank you very much.
Could you please add macOS Mojave (10.14) compatibility?
Thank you very much

**Comment by lihaoyun6** [comment]
> Great work. Thank you very much.
> Could you please add macOS Mojave (10.14) compatibility?
> Thank you very much

You can install Parallels Desktop 17 released by TNT on an older version of macOS.
