### ISSUE TITLE
启动不了，刚过期

### ISSUE THREAD

**Issue by kevon2019** [lihaoyun6/PD-Runner#61]
太难了，今天过期，然而启动不了17.0

**Comment by lihaoyun6** [comment]
> 太难了，今天过期，然而启动不了17.0

可以方便贴一下运行日志吗. 获取日志的方法为:
右键单击PD Runner的文件, 选择"显示包内容". 然后依次进入Contents > MacOS目录并双击其中的"PD Runner"文件
启动后尝试去复现一下刚刚的操作, 然后把弹出窗口中的日志信息复制或截图发上来就可以了

**Comment by kevon2019** [comment]
明天回复，170版本的，今天刚过期启动不了。
表现为虚拟机停止，pd警告，启动器菜单栏隐藏了。



| |
***@***.***
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 22:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [lihaoyun6/PD-Runner] 启动不了，刚过期 (Issue #61) |

太难了，今天过期，然而启动不了17.0

可以方便贴一下运行日志吗. 获取日志的方法为:
右键单击PD Runner的文件, 选择"显示包内容". 然后依次进入Contents > MacOS目录并双击其中的"PD Runner"文件
启动后尝试去复现一下刚刚的操作, 然后把弹出窗口中的日志信息复制或截图发上来就可以了

**Comment by Asura88** [comment]
启动不了，刚过期 170版本的，今天刚过期启动不了。
表现为虚拟机停止，pd警告，启动器菜单栏隐藏了。

**Comment by kevon2019** [comment]
截图如下



| |
***@***.***
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 23:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [lihaoyun6/PD-Runner] 启动不了，刚过期 (Issue #61) |

启动不了，刚过期 170版本的，今天刚过期启动不了。
表现为虚拟机停止，pd警告，启动器菜单栏隐藏了。

**Comment by lihaoyun6** [comment]
> 截图如下 | | ***@***.*** | | ***@***.*** | 发自 网易邮箱大师
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2021年11月17日 23:59 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [lihaoyun6/PD-Runner] 启动不了，刚过期 (Issue #61) | 启动不了，刚过期 170版本的，今天刚过期启动不了。 表现为虚拟机停止，pd警告，启动器菜单栏隐藏了。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.  

<img width="914" alt="Xnip2021-11-18_12-41-01" src="https://user-images.githubusercontent.com/16348097/142352986-d7b4b5bc-5811-4bdb-9d01-6c1cc40b9b4a.png">
亲不要用邮件回复, 我看不到你发的截图

**Comment by lihaoyun6** [comment]
> 启动不了，刚过期 170版本的，今天刚过期启动不了。
> 表现为虚拟机停止，pd警告，启动器菜单栏隐藏了。

可以方便贴一下运行日志吗. 获取日志的方法为:
右键单击PD Runner的文件, 选择"显示包内容". 然后依次进入Contents > MacOS目录并双击其中的"PD Runner"文件
启动后尝试去复现一下刚刚的操作, 然后把弹出窗口中的日志信息复制或截图发上来就可以了

**Comment by Asura88** [comment]
Last login: Thu Nov 18 01:00:38 on ttys000
mannix@MannixdeMacBook-Pro ~ % /Applications/PD\ Runner.app/Contents/MacOS/PD\ Runner ; exit;
2021-11-18 14:16:03.6190 Check helper status...
2021-11-18 14:16:03.6200 Helper installed.
2021-11-18 14:16:03.6230 Run loop...
2021-11-18 14:16:03.6470 Installed version: 0.1.12, InBundle version: 0.1.12
2021-11-18 14:16:03.6470 Helper installed.
2021-11-18 14:16:03.9210 VM list: [Windows 7:win-7,Windows 10:win-10]

**Comment by lihaoyun6** [comment]
> Last login: Thu Nov 18 01:00:38 on ttys000
> mannix@MannixdeMacBook-Pro ~ % /Applications/PD\ Runner.app/Contents/MacOS/PD\ Runner ; exit;
> 2021-11-18 14:16:03.6190 Check helper status...
> 2021-11-18 14:16:03.6200 Helper installed.
> 2021-11-18 14:16:03.6230 Run loop...
> 2021-11-18 14:16:03.6470 Installed version: 0.1.12, InBundle version: 0.1.12
> 2021-11-18 14:16:03.6470 Helper installed.
> 2021-11-18 14:16:03.9210 VM list: [Windows 7:win-7,Windows 10:win-10]

你需要用PD Runner进行一下开机操作, 才会有那部分的实时日志. 目前这个日志只是软件初始化阶段的

**Comment by kevon2019** [comment]
开机不了啊，win11停止运行



| |
***@***.***
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月18日 19:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [lihaoyun6/PD-Runner] 启动不了，刚过期 (Issue #61) |

Last login: Thu Nov 18 01:00:38 on ttys000
***@***.*** ~ % /Applications/PD\ Runner.app/Contents/MacOS/PD\ Runner ; exit;
2021-11-18 14:16:03.6190 Check helper status...
2021-11-18 14:16:03.6200 Helper installed.
2021-11-18 14:16:03.6230 Run loop...
2021-11-18 14:16:03.6470 Installed version: 0.1.12, InBundle version: 0.1.12
2021-11-18 14:16:03.6470 Helper installed.
2021-11-18 14:16:03.9210 VM list: [Windows 7:win-7,Windows 10:win-10]

你需要用PD Runner进行一下开机操作, 才会有那部分的实时日志. 目前这个日志只是软件初始化阶段的

**Comment by lihaoyun6** [comment]
> 开机不了啊，win11停止运行 | | ***@***.*** | | ***@***.*** | 发自 网易邮箱大师
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2021年11月18日 19:23 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [lihaoyun6/PD-Runner] 启动不了，刚过期 (Issue #61) | Last login: Thu Nov 18 01:00:38 on ttys000 ***@***.*** ~ % /Applications/PD\ Runner.app/Contents/MacOS/PD\ Runner ; exit; 2021-11-18 14:16:03.6190 Check helper status... 2021-11-18 14:16:03.6200 Helper installed. 2021-11-18 14:16:03.6230 Run loop... 2021-11-18 14:16:03.6470 Installed version: 0.1.12, InBundle version: 0.1.12 2021-11-18 14:16:03.6470 Helper installed. 2021-11-18 14:16:03.9210 VM list: [Windows 7:win-7,Windows 10:win-10] 你需要用PD Runner进行一下开机操作, 才会有那部分的实时日志. 目前这个日志只是软件初始化阶段的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你要进行一下开机操作...听不懂吗? 很难理解吗?
我不是让你成功, 我是让你去用一下这个功能, 这样不管是否成功, 他都会输出日志
如果失败了, 我根据日志就能判断出问题在哪

**Comment by lihaoyun6** [comment]
@kevon2019 还有你不要总用那个邮箱回复. 我看不到你所谓的截图. 你再这样我就关闭issue了. 我也不是一天到晚闲的没事专门伺候你的

**Comment by Asura88** [comment]
![image](https://user-images.githubusercontent.com/25000885/142587991-4657cd78-2892-4965-900a-18bab6da7187.png)

**Comment by lihaoyun6** [comment]
@Asura88 这个不是启动器的问题, 是创建虚拟机的时候没设置好
创建虚拟机的时候一定要记得勾选左下角的"手动安装操作系统", 不勾选的话最后就会卡在这过不去
