### ISSUE TITLE
虚机的安全性中的回滚模式中的询问不起作用，关机时就自动选择了放弃选项

### ISSUE THREAD

**Issue by aaabbbaaa** [lihaoyun6/PD-Runner#62]
虚机的安全性中的回滚模式中的询问不起作用，关机时就自动选择了放弃选项，并不会弹出对话框进行询问。

**Comment by lihaoyun6** [comment]
> 虚机的安全性中的回滚模式中的询问不起作用，关机时就自动选择了放弃选项，并不会弹出对话框进行询问。

经测试, 这是PD的bug, 不是启动器的bug
如果在虚拟机里面使用系统的"关机"操作, 就无法弹出那个询问对话框
而使用 菜单栏>"操作">"关闭" 来对虚拟机进行关机的话就会正常弹出询问对话框

**Comment by aaabbbaaa** [comment]
我这边是win11的操作系统，我目前的测试结果是，如果用PD自身打开的虚拟机用系统关闭操作是会弹出对话框的，用启动器启动的情况下，系统的关闭操作不会弹出对话框，但是用你提供的方案，通过菜单关闭操作确实会弹出对话框
