### ISSUE TITLE
Hello, how do I do this, I have tried, can not continue to try

### ISSUE THREAD

**Issue by jinxiangqiang** [lihaoyun6/PD-Runner#63]
![image](https://user-images.githubusercontent.com/21325727/142344763-966ab748-45f4-487d-8649-8a0d8e40877e.png)

**Comment by lihaoyun6** [comment]
(虽然理论上来说试用过期并不会影响PD Runner的使用)
先登出PD账号并关闭PD. 然后把系统时间调整到2021年9月1日. 之后再打开PD, 并尝试重新申请试用期

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue

**Comment by Saggitus007** [comment]
I tried it and it worked will this giv the trial issues cos l had to update the pd runner to 0.2.8 though thanks for the effort made
