### ISSUE TITLE
什么时候能增加对macOS虚拟机的启动与关机选项

### ISSUE THREAD

**Issue by xiaobai151** [lihaoyun6/PD-Runner#66]
如题，希望下个版本加入此功能

**Comment by lihaoyun6** [comment]
> 如题，希望下个版本加入此功能

没有太理解您的需求, PD Runner不挑虚拟机系统类型, 只要是PD虚拟机都支持呀

**Comment by xiaobai151** [comment]
![截屏2021-11-19 下午7 30 06](https://user-images.githubusercontent.com/68230262/142615955-a07e0e1e-038e-44cf-b67b-0b32f376b9c8.png)
而在pdrunner里没有

**Comment by xiaobai151** [comment]
可能是这次macOS虚拟机换了一种虚拟模式 设置都没有了

**Comment by lihaoyun6** [comment]
> 可能是这次macOS虚拟机换了一种虚拟模式 设置都没有了

可否在终端里执行一下这行命令, 并把结果截图发上来
`prlctl list -ao name,ostemplate -s mac`

**Comment by xiaobai151** [comment]
![截屏2021-11-20 上午10 08 15](https://user-images.githubusercontent.com/68230262/142710756-babc0f17-a1f2-42b0-9eb6-5d6b2496e331.png)

**Comment by lihaoyun6** [comment]
> ![截屏2021-11-20 上午10 08 15](https://user-images.githubusercontent.com/68230262/142710756-babc0f17-a1f2-42b0-9eb6-5d6b2496e331.png)

我已经了解到问题所在了, 正在写代码. 预计下个版本就会加入对运行在Apple Silicon Mac上的macOS虚拟机的支持

**Comment by lihaoyun6** [comment]
@xiaobai151 已经更新了v0.2.7版本, 添加了对Apple Silicon Mac上的macOS虚拟机的支持
