### ISSUE TITLE
PD Runner 正在尝试安装新帮助程序工具

### ISSUE THREAD

**Issue by 1163895390wjh** [lihaoyun6/PD-Runner#68]
系统：12.0.1 （Inter CPU）

PD版本：版本 17.1.0 (51516)
PD Runner 版本：0.2.6

打开PD Runner时提示，“PD Runner 正在尝试安装新帮助程序工具”，需要输入密码，输入密码后提示“帮助程序安装失败，Error Domain=CFErrorDomainLaunchd Code=4 "(null)"”

运行了`sudo launchctl enable system/com.lihaoyun6.PD-Runner-Helper`也没反应
用其它工具卸载了再重装也不行

如下图
![image](https://user-images.githubusercontent.com/44250675/142569840-8766f758-66e5-46f9-8e2c-ecce719ea535.png)

![image](https://user-images.githubusercontent.com/44250675/142569742-432dbd5b-dafc-4a89-8e8e-9332f47e7b06.png)

**Comment by lihaoyun6** [comment]
@1163895390wjh  试试最新版能不能正常使用

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue
