### ISSUE TITLE
可以自定义多系统的排列顺序吗？

### ISSUE THREAD

**Issue by xuewencao** [lihaoyun6/PD-Runner#69]
不影响使用，就是有点强迫症。

**Comment by lihaoyun6** [comment]
> 不影响使用，就是有点强迫症。

应该是不会添加这个功能, 抱歉

**Comment by xuewencao** [comment]
> > 不影响使用，但有点强迫症。
> 
> 抱歉，这个功能不会添加。

最新的0.2.10已经支持自定义排序了，非常感谢。
