### ISSUE TITLE
闪退MACOS 12.0.1

### ISSUE THREAD

**Issue by bolong123** [lihaoyun6/PD-Runner#7]
0.1.10版本 启动PD17.1，闪退

**Comment by lihaoyun6** [comment]
> 一样闪退 m1芯片 macOS monterey 12.0.1

这边上传一个debug版本的app, 这个版本可以输出更多的log信息.
请先使用包中附带的Uninstall Helper工具清除当前安装的运行助理.
然后右键点击包中的PD Runner, 选择"显示包内容", 并进入Contents/MacOS, 然后双击运行其中的PD Runner文件
并再把运行的截图回复上来, 方便我确认问题位置, 谢谢
[PD Runner Debug.zip](https://github.com/lihaoyun6/PD-Runner/files/7445877/PD.Runner.Debug.zip)

**Comment by lihaoyun6** [comment]
@zhuyuanmin @AlexsanderShaw @bolong123  
更新了v0.1.11, 理论上来说几位的遇到的bug应该是同一个, 这次更新已经修复了, 可以尝试下载使用看看
