### ISSUE TITLE
无法连接parallels服务

### ISSUE THREAD

**Issue by fff911** [lihaoyun6/PD-Runner#72]
求教！打开pd和win7之后，打开这个app，第一行显示“无法连接parallels服务”。

**Comment by lihaoyun6** [comment]
> 

请尝试在终端执行下面这条命令, 并将运行结果截图发上来, 谢谢
`prlctl list -ao name,ostemplate`

**Comment by fff911** [comment]
![截屏2021-11-20 下午4 30 43](https://user-images.githubusercontent.com/56096740/142720091-9c98e189-0052-44c4-9355-ca2e76b7389d.png)

**Comment by lihaoyun6** [comment]
> ![截屏2021-11-20 下午4 30 43](https://user-images.githubusercontent.com/56096740/142720091-9c98e189-0052-44c4-9355-ca2e76b7389d.png)

请截全图, 这样我没办法判断

**Comment by fff911** [comment]
![截屏2021-11-20 下午5 00 08](https://user-images.githubusercontent.com/56096740/142720674-12ea224d-97f4-491d-8e4a-e0140fe0d512.png
![截屏2021-11-20 下午5 00 55](https://user-images.githubusercontent.com/56096740/142720720-983e36b6-ff7b-4d2a-b017-47c18099e8b4.png)
)这样行吗？

**Comment by fff911** [comment]
![截屏2021-11-20 下午5 03 04](https://user-images.githubusercontent.com/56096740/142720745-4d1fb501-e35a-45b8-9b59-5c78d93019e8.png)

**Comment by lihaoyun6** [comment]
> ![截屏2021-11-20 下午5 00 08](https://user-images.githubusercontent.com/56096740/142720674-12ea224d-97f4-491d-8e4a-e0140fe0d512.png
> ![截屏2021-11-20 下午5 00 55](https://user-images.githubusercontent.com/56096740/142720720-983e36b6-ff7b-4d2a-b017-47c18099e8b4.png)
> )这样行吗？

不要sudo……我给你的明令里面明明没有sudo，为什么要擅自加上呢

**Comment by fff911** [comment]
抱歉，结果是这样的 
% prlctl list -ao name,ostemplate
zsh: command not found: prlctl

**Comment by lihaoyun6** [comment]
> 抱歉，结果是这样的
> % prlctl list -ao name,ostemplate
> zsh: command not found: prlctl

请再试试下面这条命令看看有什么结果
`/usr/local/bin/prlctl list -ao name,-,-,-,-,ostemplate -s mac 2>/dev/null|sed 's/[ ]*-[ ]*/-/g;s/----/:/g'`

**Comment by fff911** [comment]
****% /usr/local/bin/prlctl list -ao name,-,-,-,-,ostemplate -s mac 2>/dev/null|sed 's/[ ]*-[ ]*/-/g;s/----/:/g'
****% 没有反应，我又试了一下第一个命令% prlctl list -ao name,ostemplate
zsh: command not found: prlctl结果还是一样。

**Comment by fff911** [comment]
![截屏2021-11-20 下午7 33 25](https://user-images.githubusercontent.com/56096740/142724825-6ef220bf-c509-43ec-86e1-da7ee8135dd2.png)

**Comment by lihaoyun6** [comment]
> 

那你执行`/usr/local/bin/prlctl list -ao name,ostemplate`试试?

**Comment by fff911** [comment]
![截屏2021-11-20 下午7 35 25](https://user-images.githubusercontent.com/56096740/142724863-36369606-e189-43ce-a629-8c767259c89e.png)

**Comment by lihaoyun6** [comment]
> ![截屏2021-11-20 下午7 35 25](https://user-images.githubusercontent.com/56096740/142724863-36369606-e189-43ce-a629-8c767259c89e.png)

你可以试试把`/usr/local/bin/prlctl`和`/usr/local/bin/prlsrvctl`这两个文件删掉, 然后再次运行PD Runner试一下

**Comment by fff911** [comment]
![截屏2021-11-20 下午8 37 03](https://user-images.githubusercontent.com/56096740/142726524-2bcd26ad-5d2e-44b6-a195-4eb4edbca161.png)
还是不能连接

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue
