### ISSUE TITLE
M1 PD没法安装macos系统呢，自动下载里只有linux，自己下载好macos安装文件.app结尾的，自动转格式后提示“无法使用指定的映像，因为您的 Mac 配备了 Apple M1 芯片，不支持基于 Intel 的操作系统。”

### ISSUE THREAD

**Issue by Rhinocros** [lihaoyun6/PD-Runner#73]
M1 PD没法安装macos系统呢，自动下载里只有linux，自己下载好macos安装文件.app结尾的，自动转格式后提示“无法使用指定的映像，因为您的 Mac 配备了 Apple M1 芯片，不支持基于 Intel 的操作系统。”
![image](https://tva4.sinaimg.cn/large/006Rm27Qgy1gwlwv0kcf3j30rc0jcgwl.jpg)
![image](https://tva2.sinaimg.cn/large/006Rm27Qgy1gwlwvvmywxj30rc0jcjwp.jpg)

**Comment by lihaoyun6** [comment]
<img width="984" alt="Xnip2021-11-20_21-13-34" src="https://user-images.githubusercontent.com/16348097/142727664-6642b0c4-2392-4889-9653-391b0f13feb7.png">

**Comment by lihaoyun6** [comment]
这个不是我负责的, 和我没关系

**Comment by Saggitus007** [comment]
You have to download the arm based windows before it can work

**Comment by Rhinocros** [comment]
> You have to download the arm based windows before it can work

I want to install macos system on M1 chip
