### ISSUE TITLE
无效启动项

### ISSUE THREAD

**Issue by zhdsmy** [lihaoyun6/PD-Runner#74]
版本 0.2.7
![image](https://user-images.githubusercontent.com/8348149/142728783-185f9475-b01e-408d-bc87-56e7751acc56.png)

**Comment by lihaoyun6** [comment]
> 版本 0.2.7
> ![image](https://user-images.githubusercontent.com/8348149/142728783-185f9475-b01e-408d-bc87-56e7751acc56.png)

由于疏忽忘记对此处做错误捕获, 导致错误信息泄露到了菜单项生成器里. 已在0.2.8修复
