### ISSUE TITLE
启动之后提示未安装Parallels Desktop

### ISSUE THREAD

**Issue by zhutaofei** [lihaoyun6/PD-Runner#75]
> > > > 启动之后提示未安装Parallels Desktop
> > > > ![image](https://user-images.githubusercontent.com/13133912/141879076-26f80b29-4318-45e6-99cf-ce3c10828a38.png)
> > > > 实际上已安装，如下图
> > > > ![image](https://user-images.githubusercontent.com/13133912/141879215-3055b64d-fc49-4b89-8f28-82b867780439.png)
> > > 
> > > 
> > > 重装一下PD试试. 目前是从/usr/local/bin来索引prlctl可执行文件并以此判断PD是否安装 下个版本我改成从绝对位置来调用吧...
> > 
> > 
> > 好的，等下个版本，我这应该是之前homebrew安装的问题，导致usr/local/bin是一个文件
> 
> @lihaoyun6 安装了0.2.6版本，但是出现另外的问题，连不上服务 ![image](https://user-images.githubusercontent.com/13133912/142565562-bc7ed234-8ab4-4a7b-9e90-cba20f8035a5.png)

请尝试在终端执行下列命令, 并将运行截图回复上来, 谢谢
`/usr/local/bin/prlctl list -ao name,ostemplate -s mac`

_Originally posted by @lihaoyun6 in https://github.com/lihaoyun6/PD-Runner/issues/54#issuecomment-973923305_

**Comment by zhutaofei** [comment]
![image](https://user-images.githubusercontent.com/13133912/142855169-c8ebcefa-d2c8-46eb-8189-3a9b5d57a96a.png)
@lihaoyun6 截图如上

**Comment by Saggitus007** [comment]
What Mac os are you on cos l just installed it this evening on Monterey  and it worked fine at first complained about l should use a trail version of sort figured it out and it worked for me

**Comment by zhutaofei** [comment]
> What Mac os are you on cos l just installed it this evening on Monterey and it worked fine at first complained about l should use a trail version of sort figured it out and it worked for me

big sur

**Comment by PandengWang** [comment]
i have encountered the same issue.

**Comment by BCsl** [comment]
same issue : 未安装Parallels Desktop
```
$ /usr/local/bin/prlctl list -ao name,ostemplate -s mac
NAME                             OSTEMPLATE
Windows 11                       win-11
```

BigSur 11.4, M1

**Comment by Saggitus007** [comment]
Use the latest pd launcher you should no longer have that problem

**Comment by lihaoyun6** [comment]
长时间未回复,故关闭此issue
