### ISSUE TITLE
即使已经登陆PD帐号，依然会显示“Get the trial first!"

### ISSUE THREAD

**Issue by ryan226a** [lihaoyun6/PD-Runner#76]
一切正常使用之后，某天登出了PD的试用帐号（已到期），然后再次登陆账号后，PD runner就无法再启动了，一直显示“Get the trial first!" 报错信息。不知是不是个例。

**Comment by ryan226a** [comment]
MacOS Monterey; M1

**Comment by ryan226a** [comment]
<img width="849" alt="Screen Shot 2021-11-23 at 3 34 54 pm" src="https://user-images.githubusercontent.com/94885044/142971794-65215e57-7a11-413f-a3c3-d73a09906bef.png">

**Comment by lihaoyun6** [comment]
<img width="171" alt="Xnip2021-11-23_20-41-31" src="https://user-images.githubusercontent.com/16348097/143025760-28151616-39a5-4c80-80ad-c73692853b76.png">

**Comment by floriaaan** [comment]
And if we already claim the 14days before ?

**Comment by ryan226a** [comment]
已经试用超过14天了,再次点击申请试用会告知本机器已经试用过，无法再次申请试用。
登出之前一切可以正常使用pd runner。

**Comment by ryan226a** [comment]
<img width="575" alt="Screen Shot 2021-11-24 at 8 46 28 am" src="https://user-images.githubusercontent.com/94885044/143134362-2c46f39b-8ba3-4df4-8b64-c898c9f64750.png">

**Comment by wangkunmike** [comment]
修改系统时间可以解决试用时间过期问题

**Comment by ryan226a** [comment]
> And if we already claim the 14days before ?

Hi Floriaaan,
Did you have the same issue?

**Comment by wangkunmike** [comment]
> > And if we already claim the 14days before ?
> 
> Hi Floriaaan, Did you have the same issue?

修改系统时间可以解决

**Comment by ryan226a** [comment]
> 修改系统时间可以解决试用时间过期问题

谢谢回复，刚刚将系统时间调成手动，并设置在了当时刚刚注册试用期的第三天，但是问题依然存在。

**Comment by wangkunmike** [comment]
> > 修改系统时间可以解决试用时间过期问题
> 
> 谢谢回复，刚刚将系统时间调成手动，并设置在了当时刚刚注册试用期的第三天，但是问题依然存在。

更换一个新邮箱。我在更新版本17后是这样操作的：重新注册新的邮箱账户和修改系统时间。

**Comment by ryan226a** [comment]
> > > 修改系统时间可以解决试用时间过期问题
> > 
> > 
> > 谢谢回复，刚刚将系统时间调成手动，并设置在了当时刚刚注册试用期的第三天，但是问题依然存在。
> 
> 更换一个新邮箱。我在更新版本17后是这样操作的：重新注册新的邮箱账户和修改系统时间。

感谢建议，问题解决了。
修改时间后，还需要点击申请新试用，然后PD runner可以正常开启。之后可以把时间修改回来，不会报错。
似乎原因是：在**第一次启动**PD runner的时候，需要一个“**正在试用期以内**”的账号，而不仅仅是一个PD试用账号，第一次启动之后，便不再有这样的要求了，即使已过期。

**Comment by lihaoyun6** [comment]
PD Runner的原理是用技术手段欺骗PD, 让PD把"已过期"的许可证误认为"未过期", 从而执行我们需要的操作.
可俗话说得好: 巧妇难为无米之炊. 既然要用许可证信息来欺骗PD, 前提就是得先有一张许可证.
PD Runner只能利用现有的许可证, 没办法自己生成许可证. 所以即使试用期已过, 也千万不要退出PD账户. 
因为如果不退出的话, 使用许可证的状态只会变为"EXPIRED", 但使用许可证还是存在的. 一旦退出了, 试用许可证就会被吊销.

**Comment by floriaaan** [comment]
working thanks !
