### ISSUE TITLE
无法启动macOS虚拟机

### ISSUE THREAD

**Issue by wangkunmike** [lihaoyun6/PD-Runner#77]
您好，请问该软件可以识别macOS虚拟机吗？软件默认启动选项只有Linux和Windows，没有macOS虚拟机。

**Comment by lihaoyun6** [comment]
> 您好，请问该软件可以识别macOS虚拟机吗？软件默认启动选项只有Linux和Windows，没有macOS虚拟机。

请问您是intel用户还是M1用户?

**Comment by wangkunmike** [comment]
> > 您好，请问该软件可以识别macOS虚拟机吗？软件默认启动选项只有Linux和Windows，没有macOS虚拟机。
> 
> 请问您是intel用户还是M1用户?

是M1，使用的是PD17

**Comment by lihaoyun6** [comment]
> > > 您好，请问该软件可以识别macOS虚拟机吗？软件默认启动选项只有Linux和Windows，没有macOS虚拟机。
> > 
> > 
> > 请问您是intel用户还是M1用户?
> 
> 是M1，使用的是PD17

`cp ~/Library/Preferences/com.parallels.Parallels\ Desktop.plist ~/Desktop`
请在终端执行一下这条命令, 执行后将桌面上出现的`com.parallels.Parallels Desktop.plist`打包发我以供调试. 谢谢

**Comment by wangkunmike** [comment]
> > > > 您好，请问该软件可以识别macOS虚拟机吗？软件默认启动选项只有Linux和Windows，没有macOS虚拟机。
> > > 
> > > 
> > > 请问您是intel用户还是M1用户?
> > 
> > 
> > 是M1，使用的是PD17
> 
> `cp ~/Library/Preferences/com.parallels.Parallels\ Desktop.plist ~/Desktop` 请在终端执行一下这条命令, 执行后将桌面上出现的`com.parallels.Parallels Desktop.plist`打包发我以供调试. 谢谢
[com.parallels.Parallels Desktop.plist.zip](https://github.com/lihaoyun6/PD-Runner/files/7604212/com.parallels.Parallels.Desktop.plist.zip)




> > > > 您好，请问该软件可以识别macOS虚拟机吗？软件默认启动选项只有Linux和Windows，没有macOS虚拟机。
> > > 
> > > 
> > > 请问您是intel用户还是M1用户?
> > 
> > 
> > 是M1，使用的是PD17
> 
> `cp ~/Library/Preferences/com.parallels.Parallels\ Desktop.plist ~/Desktop` 请在终端执行一下这条命令, 执行后将桌面上出现的`com.parallels.Parallels Desktop.plist`打包发我以供调试. 谢谢
[com.parallels.Parallels Desktop.plist.zip](https://github.com/lihaoyun6/PD-Runner/files/7604222/com.parallels.Parallels.Desktop.plist.zip)

**Comment by wangkunmike** [comment]
> > > > 您好，请问该软件可以识别macOS虚拟机吗？软件默认启动选项只有Linux和Windows，没有macOS虚拟机。
> > > 
> > > 
> > > 请问您是intel用户还是M1用户?
> > 
> > 
> > 是M1，使用的是PD17
> 
> `cp ~/Library/Preferences/com.parallels.Parallels\ Desktop.plist ~/Desktop` 请在终端执行一下这条命令, 执行后将桌面上出现的`com.parallels.Parallels Desktop.plist`打包发我以供调试. 谢谢

之前忘记查一下closed issues，发现您已经更新了对macOS系统的支持，我还没有及时更新。更新完成后可以查看到macOS虚拟机了，感谢～～

**Comment by wangkunmike** [comment]
> > > > 您好，请问该软件可以识别macOS虚拟机吗？软件默认启动选项只有Linux和Windows，没有macOS虚拟机。
> > > 
> > > 
> > > 请问您是intel用户还是M1用户?
> > 
> > 
> > 是M1，使用的是PD17
> 
> `cp ~/Library/Preferences/com.parallels.Parallels\ Desktop.plist ~/Desktop` 请在终端执行一下这条命令, 执行后将桌面上出现的`com.parallels.Parallels Desktop.plist`打包发我以供调试. 谢谢

之前忘记查一下closed issues，发现您已经更新了对macOS系统的支持，我还没有及时更新。更新完成后可以查看到macOS虚拟机了，感谢～～
如发现无法启动macOS系统，还请大家确认自己的版本是否>=0.2.8，如不是，还请更新系统。
