### ISSUE TITLE
打开软件之后，菜单栏没有图标

### ISSUE THREAD

**Issue by zhixuans** [lihaoyun6/PD-Runner#8]
第一次安装的时候，运行这个app，菜单栏里看不到图标，所以没法用，后来我卸载了pd和pd启动器，再重新安装，菜单栏可以看到图标，后来再试的时候，菜单栏又没用图标，不知道是什么问题

**Comment by lihaoyun6** [comment]
> > 启动的时候有提示你安装帮助程序吗?
> 
> 我知道问题了。。。好像是因为我pd的系统是装在u盘，我没插u盘的时候，菜单栏就没图标，插u盘的时候，能检测出系统的时候，才有图标

这边上传一个debug版本的app, 这个版本可以输出更多的log信息, 请先使用包中附带的Uninstall Helper工具清除当前安装的运行助理. 然后右键点击包中的PD Runner, 选择"显示包内容", 并进入Contents/MacOS, 然后双击运行其中的PD Runner文件
并把运行的截图回复上来, 方便我确认问题位置, 谢谢(建议在您不连接U盘的情况下测试, 尝试复现问题)
[PD Runner debug.zip](https://github.com/lihaoyun6/PD-Runner/files/7445863/PD.Runner.debug.zip)

**Comment by ad-sen** [comment]
我也是同样的问题。m1 MacBook air
<img width="893" alt="截屏2021-10-30 PM 1 54 06" src="https://user-images.githubusercontent.com/93420564/139522162-3c7ef927-bdce-4565-9a76-6156335a1d03.png">

**Comment by zhixuans** [comment]
> > > 启动的时候有提示你安装帮助程序吗?
> > 
> > 
> > 我知道问题了。。。好像是因为我pd的系统是装在u盘，我没插u盘的时候，菜单栏就没图标，插u盘的时候，能检测出系统的时候，才有图标
> 
> 这边上传一个debug版本的app, 这个版本可以输出更多的log信息, 请先使用包中附带的Uninstall Helper工具清除当前安装的运行助理. 然后右键点击包中的PD Runner, 选择"显示包内容", 并进入Contents/MacOS, 然后双击运行其中的PD Runner文件 并把运行的截图回复上来, 方便我确认问题位置, 谢谢(建议在您不连接U盘的情况下测试, 尝试复现问题) [PD Runner debug.zip](https://github.com/lihaoyun6/PD-Runner/files/7445863/PD.Runner.debug.zip)
<img width="574" alt="QQ20211030-143435@2x" src="https://user-images.githubusercontent.com/12568043/139523136-5db00167-0d8c-4249-ae4d-88d29f597d5f.png">

**Comment by lihaoyun6** [comment]
> > > > 启动的时候有提示你安装帮助程序吗?
> > > 
> > > 
> > > 我知道问题了。。。好像是因为我pd的系统是装在u盘，我没插u盘的时候，菜单栏就没图标，插u盘的时候，能检测出系统的时候，才有图标
> > 
> > 
> > 这边上传一个debug版本的app, 这个版本可以输出更多的log信息, 请先使用包中附带的Uninstall Helper工具清除当前安装的运行助理. 然后右键点击包中的PD Runner, 选择"显示包内容", 并进入Contents/MacOS, 然后双击运行其中的PD Runner文件 并把运行的截图回复上来, 方便我确认问题位置, 谢谢(建议在您不连接U盘的情况下测试, 尝试复现问题) [PD Runner debug.zip](https://github.com/lihaoyun6/PD-Runner/files/7445863/PD.Runner.debug.zip)
> 
> <img alt="QQ20211030-143435@2x" width="574" src="https://user-images.githubusercontent.com/12568043/139523136-5db00167-0d8c-4249-ae4d-88d29f597d5f.png">

谢谢反馈, 已经定位到问题了. 是在遍历虚拟机列表生成菜单时没有限制正确的下标范围导致的程序崩溃

**Comment by lihaoyun6** [comment]
> 我也是同样的问题。m1 MacBook air
> <img alt="截屏2021-10-30 PM 1 54 06" width="893" src="https://user-images.githubusercontent.com/93420564/139522162-3c7ef927-bdce-4565-9a76-6156335a1d03.png">

请尝试在终端执行
`launchctl print-disabled gui/$(id -u)|grep lihaoyun6|awk '{print $NF}'`
如果返回的结果是`true`的话, 说明PD Runner的帮助服务被系统禁用了, 可以继续在终端执行
`sudo launchctl enable gui/$(id -u)/com.lihaoyun6.PD-Runner-Helper`
并输入用户密码(输入的时候密码不可见,并不是没输入进去), 然后尝试重新打开PD Runner就可以了
第一条命令返回的结果是`false`...那我就还得仔细研究一下原因

**Comment by tengyuankoo** [comment]
<img width="621" alt="iShot2021-10-31 00 00 06" src="https://user-images.githubusercontent.com/56631063/139540500-33cb6b04-94ba-4469-bdd2-3f62b1dd144d.png">
MacBook Pro (Retina, 15-inch, Mid 2015)
官网下的版本 17.1.0 (51516)
点启动器软件没任何反应
debug运行二十分钟了没执行完

**Comment by ad-sen** [comment]
> sudo launchctl enable gui/$(id -u)/com.lihaoyun6.PD-Runner-Helper

我执行第一条后没有返回任何结果，执行第二条后依然没有解决问题

**Comment by lihaoyun6** [comment]
> > sudo launchctl enable gui/$(id -u)/com.lihaoyun6.PD-Runner-Helper
> 
> 我执行第一条后没有返回任何结果，执行第二条后依然没有解决问题

那您试试执行
`sudo launchctl enable system/com.lihaoyun6.PD-Runner-Helper`
之后再试试. 如果还是不行的话, 我暂时也没有更好的方案, 还需要后续再排查

**Comment by lihaoyun6** [comment]
> <img alt="iShot2021-10-31 00 00 06" width="621" src="https://user-images.githubusercontent.com/56631063/139540500-33cb6b04-94ba-4469-bdd2-3f62b1dd144d.png">
> 
> MacBook Pro (Retina, 15-inch, Mid 2015) 官网下的版本 17.1.0 (51516) 点启动器软件没任何反应 debug运行二十分钟了没执行完

好的, 您可以关闭这个窗口了. 我稍后会发布一个v0.1.11更新, 您可以下载使用一下看看会不会有所改观.
(正常打开既可, 不需要使用debug的启动方式)

**Comment by ad-sen** [comment]
> > > sudo launchctl enable gui/$(id -u)/com.lihaoyun6.PD-Runner-Helper
> > 
> > 
> > 我执行第一条后没有返回任何结果，执行第二条后依然没有解决问题
> 
> 那您试试执行 `sudo launchctl enable system/com.lihaoyun6.PD-Runner-Helper` 之后再试试. 如果还是不行的话, 我暂时也没有更好的方案, 还需要后续再排查

问题解决！谢谢您

**Comment by tengyuankoo** [comment]
> > <img alt="iShot2021-10-31 00 00 06" width="621" src="https://user-images.githubusercontent.com/56631063/139540500-33cb6b04-94ba-4469-bdd2-3f62b1dd144d.png">
> > MacBook Pro (Retina, 15-inch, Mid 2015) 官网下的版本 17.1.0 (51516) 点启动器软件没任何反应 debug运行二十分钟了没执行完
> 
> 好的, 您可以关闭这个窗口了. 我稍后会发布一个v0.1.11更新, 您可以下载使用一下看看会不会有所改观. (正常打开既可, 不需要使用debug的启动方式)

解决了，谢谢

**Comment by lihaoyun6** [comment]
@zhixuans  
问题已经解决, 更新v0.1.11版本既可

**Comment by zhixuans** [comment]
> @zhixuans 问题已经解决, 更新v0.1.11版本既可

非常感谢
