### ISSUE TITLE
Error Domain=CFErrorDomainLaunchd Code=9 "(null)"

### ISSUE THREAD

**Issue by vycz** [lihaoyun6/PD-Runner#80]
帮助程序安装失败
Error Domain=CFErrorDomainLaunchd Code=9 "(null)"

**Comment by lihaoyun6** [comment]
> 帮助程序安装失败
> Error Domain=CFErrorDomainLaunchd Code=9 "(null)"

主页翻到底, 能看到解决方案

**Comment by OceansDeep219** [comment]
failed to install the PD runer:  Error Domain=CFErrorDomainLaunchd Code=9 "(null)", MacOS: Monterey12.1 (m1 pro)

**Comment by OceansDeep219** [comment]
> failed to install the PD runer: Error Domain=CFErrorDomainLaunchd Code=9 "(null)", MacOS: Monterey12.1 (m1 pro)

被柠檬拦截了
