### ISSUE TITLE
用此工具打开虚拟机后，虚拟机自动进入暂停状态，菜单中点恢复后，又跳出了试用期已结束的提示

### ISSUE THREAD

**Issue by horuszhao** [lihaoyun6/PD-Runner#82]
用此工具打开虚拟机后，虚拟机自动进入暂停状态，菜单中点恢复后，又跳出了试用期已结束的提示

**Comment by horuszhao** [comment]
版本17.1.0（51516）
现在通过个性系统时间可以打开虚拟机，除了改系统时间还有其它方法吗？求教

**Comment by StephenKingJJY** [comment]
17.1.0（51516）一样的问题

**Comment by abcmiao** [comment]
你们操作有问题吧，在菜单栏勾选上屏蔽过期警告。然后还是在菜单选择启动，就会出现正在恢复。

**Comment by abcmiao** [comment]
> 版本17.1.0（51516） 现在通过个性系统时间可以打开虚拟机，除了改系统时间还有其它方法吗？求教

这软件就是解决这个问题的，我目前装的最新版，在paralles打开的情况下，关掉windows系统，然后在菜单栏选windows系统点启动

**Comment by StephenKingJJY** [comment]
用此工具打开虚拟机后，虚拟机自动进入暂停状态。然后再次使用工具启动可以解决问题。

**Comment by Riptide3** [comment]
> 用此工具打开虚拟机后，虚拟机自动进入暂停状态。然后再次使用工具启动可以解决问题。

不行啊，没用

**Comment by rongpengli** [comment]
每次自动暂停，不要直接在界面上点击，再点一下PD runner里面的启动，就可以打开了

**Comment by k2y1982** [comment]
将系统时间调至软件试用过期以前的月份，然后打开parallels，再打开pd,最后将系统时间自动同步到现在。

**Comment by lihaoyun6** [comment]
未能提供更多有效信息, 故关闭此issue

**Comment by horuszhao** [comment]
> > 版本17.1.0（51516） 现在通过个性系统时间可以打开虚拟机，除了改系统时间还有其它方法吗？求教
> 
> 这软件就是解决这个问题的，我目前装的最新版，在paralles打开的情况下，关掉windows系统，然后在菜单栏选windows系统点启动

还是不行，黑屏了，一会显示虚拟机处于暂停状态，再次点击启动，又跳出了过期的窗口，再通过此工具点击启动，又黑屏，继而暂停，好像根本没用
