### ISSUE TITLE
Make the app installation process easier

### ISSUE THREAD

**Issue by rakleed** [lihaoyun6/PD-Runner#86]
Could you please make the process of installing the app more convenient either by making a DMG file with the Applications folder and the app itself or immediately after launching, prompt the user to move the app to the Applications folder (if you determine that the app is not launched from the Applications folder)?

**Comment by slipttees** [comment]
I have one. :-)

<img width="796" alt="Captura de Tela 2021-11-29 às 21 24 00" src="https://user-images.githubusercontent.com/25433004/143963303-fbabd225-009e-4e22-8aea-73e4f457daac.png">

**Comment by slipttees** [comment]
Fix is v0.2.12!

**Comment by lihaoyun6** [comment]
<img width="618" alt="Xnip2021-11-30_16-45-32" src="https://user-images.githubusercontent.com/16348097/144015323-9867dcfe-ff6b-480f-ae8c-685cc671f3d1.png">  
@rakleed @slipttees

Wow, that's a good idea! I decided to package the app into `.dmg` from [v0.1.12](https://github.com/lihaoyun6/PD-Runner/releases/tag/0.2.12)

**Comment by slipttees** [comment]
Very Nice... maybe put a little background! :-)

**Comment by lihaoyun6** [comment]
> Very Nice... maybe put a little background! :-)

😄The next update will have a more beautiful background.
