### ISSUE TITLE
无法正常打开pd runner

### ISSUE THREAD

**Issue by beergold** [lihaoyun6/PD-Runner#88]
![image](https://user-images.githubusercontent.com/54296655/143981662-008c7a0d-7f8b-4458-abf5-5384fff3126c.png)
如上图，我现在是之前装过pd试用过，但是后来我把pd删了，现在官网提示我无法继续试用了，但是你的软件提示没找到试用日期，导致我无法正常使用pd runner

**Comment by lihaoyun6** [comment]
@beergold 
卸载PD(或退出PD账户)会导致许可证被吊销. 而PD Runner必须要求具有许可证才能工作(即使许可证已过期).
现在您可以尝试退出PD, 并将系统日期调至2021.09.01. 然后重新启动PD, 再登录账户申请试用期, 最后将系统时间复原.
理论上这样操作之后, 就可以重新获得许可证.

**Comment by lihaoyun6** [comment]
@beergold 如果使用9月1日还是不成功的话, 可以尝试继续往前调(8月1日, 7月1日之类的)
