### ISSUE TITLE
请问有没有可能可以隐藏菜单栏图标

### ISSUE THREAD

**Issue by AlickH** [lihaoyun6/PD-Runner#90]
现在已经可以用AppleScript进行操作了
配合Alfred已经可以不用通过菜单栏图标操作了
请问有没有可能隐藏菜单栏图标来节省菜单栏空间呢

**Comment by lihaoyun6** [comment]
@AlickH 
目前PD Runner唯一的界面入口只有菜单栏图标, 隐藏它倒是不难. 问题在于隐藏了之后, 如果用户想让它再显示...该怎么设置

**Comment by AlickH** [comment]
> @AlickH
> 目前PD Runner唯一的界面入口只有菜单栏图标, 隐藏它倒是不难. 问题在于隐藏了之后, 如果用户想让它再显示...该怎么设置

像popclip隐藏菜单栏图标后可以在应用运行的情况下再次打开应用以显示菜单栏图标 这时候就可以设置是否隐藏菜单栏图标了

**Comment by lihaoyun6** [comment]
@AlickH 
我思考了一下, 既然是自动化用户会用到的功能, 我认为就把这个功能也添加到命令吧.
 通过AppleScript来控制图标的隐藏/显示, 并在下次启动时生效. 

比如隐藏图标就是:  
```AppleScript
tell application "PD Runner" to (hide icon) and (quit)
```
显示图标就是:
```AppleScript
tell application "PD Runner" to (show icon) and (quit)
```

**Comment by lihaoyun6** [comment]
@AlickH 
最终确定在v0.2.13中加入这个功能, 使用AppleScript来控制菜单栏图标的显示与隐藏  

隐藏/显示菜单栏图标(下次启动时生效):  
```AppleScript
tell application "PD Runner" to hide icon
tell application "PD Runner" to show icon
```

**Comment by AlickH** [comment]
> @AlickH 最终确定在v0.2.13中加入这个功能, 使用AppleScript来控制菜单栏图标的显示与隐藏
> 
> 隐藏/显示菜单栏图标(下次启动时生效):
> 
> ```applescript
> tell application "PD Runner" to hide icon
> tell application "PD Runner" to show icon
> ```

谢谢大佬🙏
