### ISSUE TITLE
does not work on macos monterey

### ISSUE THREAD

**Issue by 3skelion** [lihaoyun6/PD-Runner#91]
does not work on macos monterey

Writes; Failed to open PD Runner program

**Comment by Terrormixer3000** [comment]
works for me on 12.0.1

**Comment by lihaoyun6** [comment]
@3skelion 
How to get logs:
1. Right click "PD Runner. app", and then click "Show Package Contents"
2. Go to "Contents" > "MacOS" folder
3. Double click the "PD Runner" file to start PD Runner in verbose mode
4. Copy or screenshot the contents in the Terminal window, and then reply it to me

**Comment by 3skelion** [comment]
Yay! version v.0.2.13 is up and running. Thanks

**Comment by zcgg2zhmm** [comment]
@lihaoyun6 

![image](https://user-images.githubusercontent.com/29967092/144367089-6df34337-b109-403a-97bf-40d7640a700f.png)

pd-runner version： 0.2.13
pd version：17.1.0 (51516)

**Comment by lihaoyun6** [comment]
@zcgg2zhmm 
虽然我不对运行在测试版macOS而出现的任何问题负责.
但您可以尝试使用Uninstall-Helper彻底卸载旧版帮助程序, 之后再运行新版. 看看是否会有改观
[Uninstall-Helper.zip](https://github.com/lihaoyun6/PD-Runner/files/7638887/Uninstall-Helper.zip)

**Comment by lihaoyun6** [comment]
@zcgg2zhmm 
macOS 12.1 Beta4的"time daemon"守护进程可能有bug. 
我今晚会在v0.2.14更新中加入对macOS 12.1 Beta4的支持.

There may be a bug in the "time daemon" of macOS 12.1 Beta4.
I will add support for mac OS 12.1 Beta4 in the PD Runner v0.2.14 tonight.

**Comment by zcgg2zhmm** [comment]
> @zcgg2zhmm macOS 12.1 Beta4的"time daemon"守护进程可能有bug. 我今晚会在v0.2.14更新中加入对macOS 12.1 Beta4的支持.
> 
> There may be a bug in the "time daemon" of macOS 12.1 Beta4. I will add support for mac OS 12.1 Beta4 in the PD Runner v0.2.14 tonight.

@lihaoyun6 牛批~~ 666
