### ISSUE TITLE
pd17.1.1 装的win11  连不上网

### ISSUE THREAD

**Issue by jhtnba** [lihaoyun6/PD-Runner#93]
pd版本 17.1.1 (51537)    macos 12.0.1   装的win11  连不上网，虽然显示已经连接，但上不去

**Comment by lihaoyun6** [comment]
> pd版本 17.1.1 (51537) macos 12.0.1 装的win11 连不上网，虽然显示已经连接，但上不去

我这边暂时没有合适的测试环境, 请先确认不是PD的问题.

**Comment by lihaoyun6** [comment]
长时间未回复, 故关闭此issue
