### ISSUE TITLE
PD_runner does not work for new VM installed after trial

### ISSUE THREAD

**Issue by softdevpro3** [lihaoyun6/PD-Runner#95]
PD_runner does not work for new VM installed after trial.
How can solve this problem?

**Comment by lihaoyun6** [comment]
> PD_runner does not work for new VM installed after trial.
> How can solve this problem?  

<img width="984" alt="Xnip2021-12-02_11-37-36" src="https://user-images.githubusercontent.com/16348097/144353415-71247706-3213-4663-8db7-fd61fe9e4f80.png">

When you create a virtual machine, be sure to check "Install operating system manually", otherwise it will be stuck in the last step.

**Comment by lihaoyun6** [comment]
I haven't gotten a reply for a long time. So this issue will be closed.
