### ISSUE TITLE
“com.lihaoyun6.PD-Runner-Helper” will damage your computer.

### ISSUE THREAD

**Issue by xiebruce** [lihaoyun6/PD-Runner#97]
之前没问题，一段时间没开过之后，现在开，一直显示这个报错，关掉又自动弹出来

![image](https://user-images.githubusercontent.com/13575500/144353483-d6809647-732d-4bff-8fa3-e86e6513d729.png)

我没有安装cleanmymacX之类的，现在这个截图的界面，我关掉又跳出来，找进程找不到，不知道是哪个进程让它跳出来的，最终我只能删掉`com.lihaoyun6.PD-Runner-Helper`这个文件才停止跳.....

---

删除这个helper之后，后来我安装了新版本`0.2.13`，它不跳了

**Comment by lihaoyun6** [comment]
@xiebruce 因为在版本迭代期间, 我的临时开发者证书过期了一次, 旧证书失效了. 所以旧版的程序会报毒(实际上没有毒, 只是因为证书过期了, 苹果不承认了而已)

**Comment by xiebruce** [comment]
> @xiebruce 因为在版本迭代期间, 我的临时开发者证书过期了一次, 旧证书失效了. 所以旧版的程序会报毒(实际上没有毒, 只是因为证书过期了, 苹果不承认了而已)

了解！我也不认为有毒哈哈，只是不知道为什么，现在知道了。
