### ISSUE TITLE
What happens if i forget to delete it within 24 hrs?

### ISSUE THREAD

**Issue by procrafter820** [lihaoyun6/PD-Runner#99]
![image](https://user-images.githubusercontent.com/70203048/144362118-b2074b90-c100-4b37-8fb8-88dc6c8fa0f2.png)

**Comment by me450722457** [comment]
Santa will forget to give you a present

**Comment by procrafter820** [comment]
> Santa will forget to give you a present
JOKE!!!!!!!!!!!!!
I didn't ask that,wanted to know that will it affect my system

**Comment by lihaoyun6** [comment]
@procrafter820 
PD Runner will not damage your computer. 
But if you abuse PD Runner, then you will take all the responsibility yourself (If Parallels sue you for using pirated software)  
And I won't take any responsibility, because i told you in advance
